/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`list_market_order_book_subscriptions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListMarketOrderBookSubscriptionsError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`subscribe_market_order_book`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SubscribeMarketOrderBookError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`unsubscribe_market_order_book`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UnsubscribeMarketOrderBookError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// List active order book subscriptions
pub async fn list_market_order_book_subscriptions(
    configuration: &configuration::Configuration,
    instrument_id: Option<&str>,
) -> Result<
    models::ListTradingAccountSubscriptions200Response,
    Error<ListMarketOrderBookSubscriptionsError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_instrument_id = instrument_id;

    let uri_str = format!(
        "{}/api/v3/market/subscription/orderBook/list",
        configuration.base_path
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_instrument_id {
        req_builder = req_builder.query(&[("instrumentId", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListTradingAccountSubscriptions200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListTradingAccountSubscriptions200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListMarketOrderBookSubscriptionsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Subscribe to real-time order book updates
pub async fn subscribe_market_order_book(
    configuration: &configuration::Configuration,
    subscribe_market_order_book_request: Option<models::SubscribeMarketOrderBookRequest>,
) -> Result<models::SubscribeTradingAccount200Response, Error<SubscribeMarketOrderBookError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_subscribe_market_order_book_request = subscribe_market_order_book_request;

    let uri_str = format!(
        "{}/api/v3/market/subscription/orderBook/subscribe",
        configuration.base_path
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_subscribe_market_order_book_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SubscribeTradingAccount200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SubscribeTradingAccount200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SubscribeMarketOrderBookError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Unsubscribe from real-time order book updates
pub async fn unsubscribe_market_order_book(
    configuration: &configuration::Configuration,
    unsubscribe_request: Option<models::UnsubscribeRequest>,
) -> Result<models::SubscribeTradingAccount200Response, Error<UnsubscribeMarketOrderBookError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_unsubscribe_request = unsubscribe_request;

    let uri_str = format!(
        "{}/api/v3/market/subscription/orderBook/unsubscribe",
        configuration.base_path
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_unsubscribe_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SubscribeTradingAccount200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SubscribeTradingAccount200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UnsubscribeMarketOrderBookError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
