/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`delete_market_instrument`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteMarketInstrumentError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_market_security`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteMarketSecurityError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`disable_market_instrument`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DisableMarketInstrumentError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`enable_market_instrument`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EnableMarketInstrumentError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_market_order_book`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetMarketOrderBookError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_market_instruments`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListMarketInstrumentsError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_market_order_books`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListMarketOrderBooksError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_market_securities`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListMarketSecuritiesError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_market_venues`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListMarketVenuesError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`sync_market_instruments`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SyncMarketInstrumentsError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`sync_market_securities`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SyncMarketSecuritiesError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}


/// Delete a market instrument
pub async fn delete_market_instrument(configuration: &configuration::Configuration, delete_market_instrument_request: Option<models::DeleteMarketInstrumentRequest>) -> Result<models::DeleteMarketInstrument200Response, Error<DeleteMarketInstrumentError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_delete_market_instrument_request = delete_market_instrument_request;

    let uri_str = format!("{}/api/v3/market/instrument/delete", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_delete_market_instrument_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteMarketInstrument200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteMarketInstrument200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteMarketInstrumentError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete a financial security
pub async fn delete_market_security(configuration: &configuration::Configuration, delete_market_security_request: Option<models::DeleteMarketSecurityRequest>) -> Result<models::DeleteMarketSecurity200Response, Error<DeleteMarketSecurityError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_delete_market_security_request = delete_market_security_request;

    let uri_str = format!("{}/api/v3/market/security/delete", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_delete_market_security_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteMarketSecurity200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteMarketSecurity200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteMarketSecurityError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Disable a market instrument for trading
pub async fn disable_market_instrument(configuration: &configuration::Configuration, disable_market_instrument_request: Option<models::DisableMarketInstrumentRequest>) -> Result<models::EnableMarketInstrument200Response, Error<DisableMarketInstrumentError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_disable_market_instrument_request = disable_market_instrument_request;

    let uri_str = format!("{}/api/v3/market/instrument/disable", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_disable_market_instrument_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnableMarketInstrument200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnableMarketInstrument200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DisableMarketInstrumentError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Enable a market instrument for trading
pub async fn enable_market_instrument(configuration: &configuration::Configuration, enable_market_instrument_request: Option<models::EnableMarketInstrumentRequest>) -> Result<models::EnableMarketInstrument200Response, Error<EnableMarketInstrumentError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_enable_market_instrument_request = enable_market_instrument_request;

    let uri_str = format!("{}/api/v3/market/instrument/enable", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_enable_market_instrument_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnableMarketInstrument200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnableMarketInstrument200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<EnableMarketInstrumentError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get order book for a specific instrument. instrumentId or venue+symbol
pub async fn get_market_order_book(configuration: &configuration::Configuration, instrument_id: Option<&str>, venue: Option<models::Venue>, symbol: Option<&str>, depth: Option<i32>) -> Result<models::GetMarketOrderBook200Response, Error<GetMarketOrderBookError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_instrument_id = instrument_id;
    let p_query_venue = venue;
    let p_query_symbol = symbol;
    let p_query_depth = depth;

    let uri_str = format!("{}/api/v3/market/orderBook/get", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_instrument_id {
        req_builder = req_builder.query(&[("instrumentId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_venue {
        req_builder = req_builder.query(&[("venue", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_symbol {
        req_builder = req_builder.query(&[("symbol", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_depth {
        req_builder = req_builder.query(&[("depth", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetMarketOrderBook200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetMarketOrderBook200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetMarketOrderBookError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// List available market instruments
pub async fn list_market_instruments(configuration: &configuration::Configuration, venue: Option<models::Venue>, symbols: Option<Vec<String>>, security_type: Option<models::SecurityType>, instrument_status: Option<models::InstrumentStatus>, limit: Option<i32>, offset: Option<i32>) -> Result<models::ListMarketInstruments200Response, Error<ListMarketInstrumentsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_venue = venue;
    let p_query_symbols = symbols;
    let p_query_security_type = security_type;
    let p_query_instrument_status = instrument_status;
    let p_query_limit = limit;
    let p_query_offset = offset;

    let uri_str = format!("{}/api/v3/market/instrument/list", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_venue {
        req_builder = req_builder.query(&[("venue", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_symbols {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("symbols".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("symbols", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_security_type {
        req_builder = req_builder.query(&[("securityType", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_instrument_status {
        req_builder = req_builder.query(&[("instrumentStatus", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListMarketInstruments200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListMarketInstruments200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListMarketInstrumentsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// List order books for multiple instruments
pub async fn list_market_order_books(configuration: &configuration::Configuration, instrument_ids: Option<Vec<String>>, venue: Option<models::Venue>, symbols: Option<Vec<String>>, depth: Option<i32>) -> Result<models::ListMarketOrderBooks200Response, Error<ListMarketOrderBooksError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_instrument_ids = instrument_ids;
    let p_query_venue = venue;
    let p_query_symbols = symbols;
    let p_query_depth = depth;

    let uri_str = format!("{}/api/v3/market/orderBook/list", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_instrument_ids {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("instrumentIds".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("instrumentIds", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_venue {
        req_builder = req_builder.query(&[("venue", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_symbols {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("symbols".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("symbols", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_depth {
        req_builder = req_builder.query(&[("depth", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListMarketOrderBooks200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListMarketOrderBooks200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListMarketOrderBooksError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// List available financial securities
pub async fn list_market_securities(configuration: &configuration::Configuration, venue: Option<models::Venue>, security_id: Option<&str>, limit: Option<i32>, offset: Option<i32>) -> Result<models::ListMarketSecurities200Response, Error<ListMarketSecuritiesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_venue = venue;
    let p_query_security_id = security_id;
    let p_query_limit = limit;
    let p_query_offset = offset;

    let uri_str = format!("{}/api/v3/market/security/list", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_venue {
        req_builder = req_builder.query(&[("venue", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_security_id {
        req_builder = req_builder.query(&[("securityId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListMarketSecurities200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListMarketSecurities200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListMarketSecuritiesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// List available market venues/exchanges
pub async fn list_market_venues(configuration: &configuration::Configuration, ) -> Result<models::ListMarketVenues200Response, Error<ListMarketVenuesError>> {

    let uri_str = format!("{}/api/v3/market/venue/list", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListMarketVenues200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListMarketVenues200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListMarketVenuesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Synchronize market instruments from exchanges
pub async fn sync_market_instruments(configuration: &configuration::Configuration, sync_market_instruments_request: Option<models::SyncMarketInstrumentsRequest>) -> Result<models::SyncMarketInstruments200Response, Error<SyncMarketInstrumentsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_sync_market_instruments_request = sync_market_instruments_request;

    let uri_str = format!("{}/api/v3/market/instrument/sync", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_sync_market_instruments_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SyncMarketInstruments200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SyncMarketInstruments200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SyncMarketInstrumentsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Synchronize financial securities from exchanges
pub async fn sync_market_securities(configuration: &configuration::Configuration, sync_market_securities_request: Option<models::SyncMarketSecuritiesRequest>) -> Result<models::DeleteMarketInstrument200Response, Error<SyncMarketSecuritiesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_sync_market_securities_request = sync_market_securities_request;

    let uri_str = format!("{}/api/v3/market/security/sync", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_sync_market_securities_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteMarketInstrument200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteMarketInstrument200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SyncMarketSecuritiesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

