/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`connect_trading_account`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConnectTradingAccountError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status409(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`disable_trading_account`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DisableTradingAccountError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`disconnect_trading_account`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DisconnectTradingAccountError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`enable_trading_account`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EnableTradingAccountError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_trading_account_operations`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListTradingAccountOperationsError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_trading_accounts`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListTradingAccountsError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_trading_account`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateTradingAccountError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}


/// Connect to a trading account. Returns 409 Conflict if the external account is already connected by another user.
pub async fn connect_trading_account(configuration: &configuration::Configuration, connect_trading_account_request: Option<models::ConnectTradingAccountRequest>) -> Result<models::ConnectTradingAccount200Response, Error<ConnectTradingAccountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_connect_trading_account_request = connect_trading_account_request;

    let uri_str = format!("{}/api/v3/tradingAccount/connect", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_connect_trading_account_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConnectTradingAccount200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConnectTradingAccount200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConnectTradingAccountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Disable a trading account, the trading account will be disabled and no longer available for trading.
pub async fn disable_trading_account(configuration: &configuration::Configuration, disable_trading_account_request: Option<models::DisableTradingAccountRequest>) -> Result<models::ConnectTradingAccount200Response, Error<DisableTradingAccountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_disable_trading_account_request = disable_trading_account_request;

    let uri_str = format!("{}/api/v3/tradingAccount/disable", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_disable_trading_account_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConnectTradingAccount200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConnectTradingAccount200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DisableTradingAccountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Disconnect from a trading account, all trading functions and the event stream notification will be stopped. The trading account will be archived and no longer available for trading. If the same trading account need to be connected again, please use the connect trading account API to create another new trading account.
pub async fn disconnect_trading_account(configuration: &configuration::Configuration, disconnect_trading_account_request: Option<models::DisconnectTradingAccountRequest>) -> Result<models::ConnectTradingAccount200Response, Error<DisconnectTradingAccountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_disconnect_trading_account_request = disconnect_trading_account_request;

    let uri_str = format!("{}/api/v3/tradingAccount/disconnect", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_disconnect_trading_account_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConnectTradingAccount200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConnectTradingAccount200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DisconnectTradingAccountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Enable a trading account, the trading account will be enabled and available for trading.
pub async fn enable_trading_account(configuration: &configuration::Configuration, enable_trading_account_request: Option<models::EnableTradingAccountRequest>) -> Result<models::ConnectTradingAccount200Response, Error<EnableTradingAccountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_enable_trading_account_request = enable_trading_account_request;

    let uri_str = format!("{}/api/v3/tradingAccount/enable", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_enable_trading_account_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConnectTradingAccount200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConnectTradingAccount200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<EnableTradingAccountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// List operations history for trading accounts
pub async fn list_trading_account_operations(configuration: &configuration::Configuration, trading_account_id: Option<&str>, operation_type: Option<models::OperationType>, start_time: Option<i32>, end_time: Option<i32>, limit: Option<i32>, offset: Option<i32>, cursor: Option<&str>) -> Result<models::ListTradingAccountOperations200Response, Error<ListTradingAccountOperationsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_trading_account_id = trading_account_id;
    let p_query_operation_type = operation_type;
    let p_query_start_time = start_time;
    let p_query_end_time = end_time;
    let p_query_limit = limit;
    let p_query_offset = offset;
    let p_query_cursor = cursor;

    let uri_str = format!("{}/api/v3/tradingAccount/operation/list", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_trading_account_id {
        req_builder = req_builder.query(&[("tradingAccountId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_operation_type {
        req_builder = req_builder.query(&[("operationType", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_start_time {
        req_builder = req_builder.query(&[("startTime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_end_time {
        req_builder = req_builder.query(&[("endTime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListTradingAccountOperations200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListTradingAccountOperations200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListTradingAccountOperationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// List all trading accounts
pub async fn list_trading_accounts(configuration: &configuration::Configuration, trading_account_id: Option<&str>, venue: Option<models::Venue>, account_status: Option<models::TradingAccountStatus>, user_id: Option<&str>, tenant_id: Option<&str>, limit: Option<i32>, offset: Option<i32>) -> Result<models::ListTradingAccounts200Response, Error<ListTradingAccountsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_trading_account_id = trading_account_id;
    let p_query_venue = venue;
    let p_query_account_status = account_status;
    let p_query_user_id = user_id;
    let p_query_tenant_id = tenant_id;
    let p_query_limit = limit;
    let p_query_offset = offset;

    let uri_str = format!("{}/api/v3/tradingAccount/list", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_trading_account_id {
        req_builder = req_builder.query(&[("tradingAccountId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_venue {
        req_builder = req_builder.query(&[("venue", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_account_status {
        req_builder = req_builder.query(&[("accountStatus", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_tenant_id {
        req_builder = req_builder.query(&[("tenantId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListTradingAccounts200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListTradingAccounts200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListTradingAccountsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Update trading account information
pub async fn update_trading_account(configuration: &configuration::Configuration, update_trading_account_request: Option<models::UpdateTradingAccountRequest>) -> Result<models::ConnectTradingAccount200Response, Error<UpdateTradingAccountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_update_trading_account_request = update_trading_account_request;

    let uri_str = format!("{}/api/v3/tradingAccount/update", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_update_trading_account_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConnectTradingAccount200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConnectTradingAccount200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateTradingAccountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

