/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`list_trading_account_subscriptions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListTradingAccountSubscriptionsError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`subscribe_trading_account`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SubscribeTradingAccountError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`unsubscribe_trading_account`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UnsubscribeTradingAccountError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// List active trading account subscriptions
pub async fn list_trading_account_subscriptions(
    configuration: &configuration::Configuration,
    trading_account_id: Option<&str>,
    limit: Option<i32>,
    offset: Option<i32>,
    cursor: Option<&str>,
) -> Result<
    models::ListTradingAccountSubscriptions200Response,
    Error<ListTradingAccountSubscriptionsError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_trading_account_id = trading_account_id;
    let p_query_limit = limit;
    let p_query_offset = offset;
    let p_query_cursor = cursor;

    let uri_str = format!(
        "{}/api/v3/tradingAccount/subscription/list",
        configuration.base_path
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_trading_account_id {
        req_builder = req_builder.query(&[("tradingAccountId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListTradingAccountSubscriptions200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListTradingAccountSubscriptions200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListTradingAccountSubscriptionsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Subscribe to real-time trading account updates
pub async fn subscribe_trading_account(
    configuration: &configuration::Configuration,
    subscribe_trading_account_request: Option<models::SubscribeTradingAccountRequest>,
) -> Result<models::SubscribeTradingAccount200Response, Error<SubscribeTradingAccountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_subscribe_trading_account_request = subscribe_trading_account_request;

    let uri_str = format!(
        "{}/api/v3/tradingAccount/subscription/subscribe",
        configuration.base_path
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_subscribe_trading_account_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SubscribeTradingAccount200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SubscribeTradingAccount200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SubscribeTradingAccountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Unsubscribe from real-time trading account updates
pub async fn unsubscribe_trading_account(
    configuration: &configuration::Configuration,
    unsubscribe_request: Option<models::UnsubscribeRequest>,
) -> Result<models::SubscribeTradingAccount200Response, Error<UnsubscribeTradingAccountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_unsubscribe_request = unsubscribe_request;

    let uri_str = format!(
        "{}/api/v3/tradingAccount/subscription/unsubscribe",
        configuration.base_path
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_unsubscribe_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SubscribeTradingAccount200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SubscribeTradingAccount200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UnsubscribeTradingAccountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
