/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`cancel_trade_order`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CancelTradeOrderError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_trade_orders`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListTradeOrdersError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`submit_trade_order`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SubmitTradeOrderError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    Status403(models::BaseResponse),
    Status404(models::BaseResponse),
    Status500(models::BaseResponse),
    UnknownValue(serde_json::Value),
}

/// Cancel an existing trade order
pub async fn cancel_trade_order(
    configuration: &configuration::Configuration,
    cancel_trade_order_request: Option<models::CancelTradeOrderRequest>,
) -> Result<models::CancelTradeOrder200Response, Error<CancelTradeOrderError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_cancel_trade_order_request = cancel_trade_order_request;

    let uri_str = format!("{}/api/v3/tradeOrder/cancel", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_cancel_trade_order_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CancelTradeOrder200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CancelTradeOrder200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CancelTradeOrderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// List trade orders with filtering options
pub async fn list_trade_orders(
    configuration: &configuration::Configuration,
    trade_order_id: Option<&str>,
    order_list_id: Option<&str>,
    order_status: Option<models::OrderStatus>,
    trading_account_id: Option<&str>,
    instrument_id: Option<&str>,
    start_time: Option<i32>,
    end_time: Option<i32>,
    limit: Option<i32>,
    offset: Option<i32>,
    cursor: Option<&str>,
    ascending: Option<bool>,
) -> Result<models::ListTradeOrders200Response, Error<ListTradeOrdersError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_trade_order_id = trade_order_id;
    let p_query_order_list_id = order_list_id;
    let p_query_order_status = order_status;
    let p_query_trading_account_id = trading_account_id;
    let p_query_instrument_id = instrument_id;
    let p_query_start_time = start_time;
    let p_query_end_time = end_time;
    let p_query_limit = limit;
    let p_query_offset = offset;
    let p_query_cursor = cursor;
    let p_query_ascending = ascending;

    let uri_str = format!("{}/api/v3/tradeOrder/list", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_trade_order_id {
        req_builder = req_builder.query(&[("tradeOrderId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_order_list_id {
        req_builder = req_builder.query(&[("orderListId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_order_status {
        req_builder = req_builder.query(&[("orderStatus", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_trading_account_id {
        req_builder = req_builder.query(&[("tradingAccountId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_instrument_id {
        req_builder = req_builder.query(&[("instrumentId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_start_time {
        req_builder = req_builder.query(&[("startTime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_end_time {
        req_builder = req_builder.query(&[("endTime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_ascending {
        req_builder = req_builder.query(&[("ascending", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListTradeOrders200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListTradeOrders200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListTradeOrdersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Submit a new trade order
pub async fn submit_trade_order(
    configuration: &configuration::Configuration,
    submit_trade_order_request: Option<models::SubmitTradeOrderRequest>,
) -> Result<models::SubmitTradeOrder200Response, Error<SubmitTradeOrderError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_submit_trade_order_request = submit_trade_order_request;

    let uri_str = format!("{}/api/v3/tradeOrder/submit", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_submit_trade_order_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SubmitTradeOrder200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SubmitTradeOrder200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SubmitTradeOrderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
