/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`websocket_connect`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WebsocketConnectError {
    Status400(models::BaseResponse),
    Status401(models::BaseResponse),
    UnknownValue(serde_json::Value),
}


/// **This endpoint documents the WebSocket API protocol, not a REST endpoint.**  Connect to the Cadenza WebSocket API using the Centrifugo protocol. Use the WebSocket servers listed above (`wss://cadenza-ws.algo724.com/connection/websocket` for production or `wss://cadenza-ws-uat.algo724.com/connection/websocket` for UAT).  ## Connection Flow  1. **Establish WebSocket connection** to the server URL 2. **Send connect command** with authentication token 3. **Receive connect result** with client ID and session info 4. **Subscribe to channels** for real-time updates 5. **Receive push messages** with data updates  ## Authentication  Include your JWT token in the connect command: ```json {   \"connect\": {     \"token\": \"your-jwt-token\",     \"name\": \"your-client-name\"   },   \"id\": 1 } ```  ## Available Channels  Subscribe to channels for real-time updates:  | Channel Pattern | Description | |-----------------|-------------| | `tradingAccount:{accountId}` | Trading account updates (orders, portfolio, balances) | | `market:orderBook:{instrumentId}` | Order book updates for an instrument | | `market:trade:{instrumentId}` | Trade updates for an instrument |  ## Message Format  All WebSocket messages follow the Centrifugo JSON protocol format. See the WebSocket schemas section for detailed message structures.  For complete protocol documentation, refer to: - [Centrifugo Client Protocol](https://centrifugal.dev/docs/transports/client_protocol) - [Protocol Definitions (Protobuf)](https://github.com/centrifugal/protocol/blob/master/definitions/client.proto)
pub async fn websocket_connect(configuration: &configuration::Configuration, ws_command: Option<models::WsCommand>) -> Result<(), Error<WebsocketConnectError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_ws_command = ws_command;

    let uri_str = format!("{}/connection/websocket", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_ws_command);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<WebsocketConnectError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

