/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountOperation {
    /// UUID string
    #[serde(rename = "operationId")]
    pub operation_id: uuid::Uuid,
    /// UUID string
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
    #[serde(rename = "operationType")]
    pub operation_type: models::OperationType,
    #[serde(rename = "status")]
    pub status: models::OperationStatus,
    /// Unix timestamp in milliseconds
    #[serde(rename = "createdAt")]
    pub created_at: i64,
    /// Creation timestamp in ISO 8601 format
    #[serde(rename = "createdAtDateTime", skip_serializing_if = "Option::is_none")]
    pub created_at_date_time: Option<String>,
}

impl AccountOperation {
    pub fn new(operation_id: uuid::Uuid, trading_account_id: uuid::Uuid, operation_type: models::OperationType, status: models::OperationStatus, created_at: i64) -> AccountOperation {
        AccountOperation {
            operation_id,
            trading_account_id,
            operation_type,
            status,
            created_at,
            created_at_date_time: None,
        }
    }
}

