/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthSignupRequest {
    /// User email address
    #[serde(rename = "email")]
    pub email: String,
    /// User password (minimum 8 characters)
    #[serde(rename = "password")]
    pub password: String,
    /// Optional user metadata
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl AuthSignupRequest {
    pub fn new(email: String, password: String) -> AuthSignupRequest {
        AuthSignupRequest {
            email,
            password,
            metadata: None,
        }
    }
}

