/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthUserIdentitiesInner {
    /// Identity ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// User ID
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<uuid::Uuid>,
    /// Identity provider data
    #[serde(rename = "identityData", skip_serializing_if = "Option::is_none")]
    pub identity_data: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Identity provider name (email, google, etc.)
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    /// Last sign in timestamp for this identity
    #[serde(
        rename = "lastSignInAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_sign_in_at: Option<Option<String>>,
    /// Identity creation timestamp
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Identity last update timestamp
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl AuthUserIdentitiesInner {
    pub fn new() -> AuthUserIdentitiesInner {
        AuthUserIdentitiesInner {
            id: None,
            user_id: None,
            identity_data: None,
            provider: None,
            last_sign_in_at: None,
            created_at: None,
            updated_at: None,
        }
    }
}
