/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuthUser : Authenticated user information
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthUser {
    /// User ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// User email address
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// User phone number
    #[serde(
        rename = "phone",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phone: Option<Option<String>>,
    /// Email confirmation timestamp
    #[serde(
        rename = "emailConfirmedAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email_confirmed_at: Option<Option<String>>,
    /// Phone confirmation timestamp
    #[serde(
        rename = "phoneConfirmedAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phone_confirmed_at: Option<Option<String>>,
    /// Last sign in timestamp
    #[serde(
        rename = "lastSignInAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_sign_in_at: Option<Option<String>>,
    /// User role
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    /// Account creation timestamp
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Account last update timestamp
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "appMetadata", skip_serializing_if = "Option::is_none")]
    pub app_metadata: Option<Box<models::AuthUserAppMetadata>>,
    /// User-defined metadata
    #[serde(rename = "userMetadata", skip_serializing_if = "Option::is_none")]
    pub user_metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// User identity providers (Supabase specific)
    #[serde(
        rename = "identities",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub identities: Option<Option<Vec<models::AuthUserIdentitiesInner>>>,
}

impl AuthUser {
    /// Authenticated user information
    pub fn new() -> AuthUser {
        AuthUser {
            id: None,
            email: None,
            phone: None,
            email_confirmed_at: None,
            phone_confirmed_at: None,
            last_sign_in_at: None,
            role: None,
            created_at: None,
            updated_at: None,
            app_metadata: None,
            user_metadata: None,
            identities: None,
        }
    }
}
