/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuthUserAppMetadata : Application metadata
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthUserAppMetadata {
    /// Tenant ID
    #[serde(rename = "tenantId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Option<String>>,
    /// Allowed environments
    #[serde(rename = "environments", skip_serializing_if = "Option::is_none")]
    pub environments: Option<Vec<String>>,
}

impl AuthUserAppMetadata {
    /// Application metadata
    pub fn new() -> AuthUserAppMetadata {
        AuthUserAppMetadata {
            tenant_id: None,
            environments: None,
        }
    }
}

