/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthRefreshTokenRequest {
    /// Refresh token from previous login
    #[serde(rename = "refreshToken")]
    pub refresh_token: String,
}

impl AuthRefreshTokenRequest {
    pub fn new(refresh_token: String) -> AuthRefreshTokenRequest {
        AuthRefreshTokenRequest {
            refresh_token,
        }
    }
}

