/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BalanceStatus : Status of a balance entry
/// Status of a balance entry
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BalanceStatus {
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "LOCKED")]
    Locked,

}

impl std::fmt::Display for BalanceStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Active => write!(f, "ACTIVE"),
            Self::Locked => write!(f, "LOCKED"),
        }
    }
}

impl Default for BalanceStatus {
    fn default() -> BalanceStatus {
        Self::Active
    }
}

