/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BalanceEntry {
    /// Security symbol
    #[serde(rename = "securitySymbol")]
    pub security_symbol: String,
    #[serde(rename = "securityType")]
    pub security_type: models::SecurityType,
    /// External balance ID from the exchange
    #[serde(
        rename = "externalBalanceId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub external_balance_id: Option<Option<String>>,
    /// UUID string
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
    #[serde(rename = "status")]
    pub status: models::BalanceStatus,
    /// UUID string
    #[serde(rename = "positionId", skip_serializing_if = "Option::is_none")]
    pub position_id: Option<uuid::Uuid>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "free")]
    pub free: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "locked")]
    pub locked: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "borrowed")]
    pub borrowed: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "total")]
    pub total: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "net")]
    pub net: String,
    /// Unix timestamp in milliseconds
    #[serde(rename = "updatedAt")]
    pub updated_at: i64,
    /// Last update timestamp in ISO 8601 format
    #[serde(rename = "updatedAtDateTime", skip_serializing_if = "Option::is_none")]
    pub updated_at_date_time: Option<String>,
}

impl BalanceEntry {
    pub fn new(
        security_symbol: String,
        security_type: models::SecurityType,
        trading_account_id: uuid::Uuid,
        status: models::BalanceStatus,
        free: String,
        locked: String,
        borrowed: String,
        total: String,
        net: String,
        updated_at: i64,
    ) -> BalanceEntry {
        BalanceEntry {
            security_symbol,
            security_type,
            external_balance_id: None,
            trading_account_id,
            status,
            position_id: None,
            free,
            locked,
            borrowed,
            total,
            net,
            updated_at,
            updated_at_date_time: None,
        }
    }
}
