/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BaseResponseDetails : Additional error details (optional, only present in error responses)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseResponseDetails {
    /// Error code identifier (e.g., INVALID_TOKEN, ACCESS_DENIED)
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Resource that was being accessed
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
    /// Action that was being attempted
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    /// Required permissions or roles
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<Vec<String>>,
    /// Provided permissions or roles
    #[serde(rename = "provided", skip_serializing_if = "Option::is_none")]
    pub provided: Option<Vec<String>>,
    /// Tenant ID if relevant to the error
    #[serde(rename = "tenant_id", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
    /// Request ID for tracking and debugging
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    /// Additional metadata as key-value pairs
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl BaseResponseDetails {
    /// Additional error details (optional, only present in error responses)
    pub fn new() -> BaseResponseDetails {
        BaseResponseDetails {
            code: None,
            resource: None,
            action: None,
            required: None,
            provided: None,
            tenant_id: None,
            request_id: None,
            metadata: None,
        }
    }
}

