/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelTradeOrderRequest {
    /// UUID string
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
    /// UUID string
    #[serde(rename = "tradeOrderId")]
    pub trade_order_id: uuid::Uuid,
}

impl CancelTradeOrderRequest {
    pub fn new(trading_account_id: uuid::Uuid, trade_order_id: uuid::Uuid) -> CancelTradeOrderRequest {
        CancelTradeOrderRequest {
            trading_account_id,
            trade_order_id,
        }
    }
}

