/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CollateralMode : Collateral mode - how margin is shared across positions
/// Collateral mode - how margin is shared across positions
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CollateralMode {
    #[serde(rename = "CROSS")]
    Cross,
    #[serde(rename = "ISOLATED")]
    Isolated,

}

impl std::fmt::Display for CollateralMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Cross => write!(f, "CROSS"),
            Self::Isolated => write!(f, "ISOLATED"),
        }
    }
}

impl Default for CollateralMode {
    fn default() -> CollateralMode {
        Self::Cross
    }
}

