/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectTradingAccountRequest {
    /// A list of credential IDs to be used to connect the trading account
    #[serde(rename = "credentialIds")]
    pub credential_ids: Vec<uuid::Uuid>,
    /// External trading account ID
    #[serde(rename = "externalTradingAccountId")]
    pub external_trading_account_id: String,
    /// Nickname of the trading account
    #[serde(rename = "nickname", skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
}

impl ConnectTradingAccountRequest {
    pub fn new(
        credential_ids: Vec<uuid::Uuid>,
        external_trading_account_id: String,
    ) -> ConnectTradingAccountRequest {
        ConnectTradingAccountRequest {
            credential_ids,
            external_trading_account_id,
            nickname: None,
        }
    }
}
