/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConnectTradingAccountRequest : Connect a trading account. For exchange venues, credentialIds and externalTradingAccountId are required. For Fermata venue, only venue is required (no credentials).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectTradingAccountRequest {
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<models::Venue>,
    /// Credential IDs for exchange venues. Not required for Fermata.
    #[serde(rename = "credentialIds", skip_serializing_if = "Option::is_none")]
    pub credential_ids: Option<Vec<uuid::Uuid>>,
    /// External trading account ID. Not required for Fermata.
    #[serde(
        rename = "externalTradingAccountId",
        skip_serializing_if = "Option::is_none"
    )]
    pub external_trading_account_id: Option<String>,
    /// UUID string
    #[serde(rename = "dealerAccountId", skip_serializing_if = "Option::is_none")]
    pub dealer_account_id: Option<uuid::Uuid>,
    /// Nickname of the trading account
    #[serde(rename = "nickname", skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
}

impl ConnectTradingAccountRequest {
    /// Connect a trading account. For exchange venues, credentialIds and externalTradingAccountId are required. For Fermata venue, only venue is required (no credentials).
    pub fn new() -> ConnectTradingAccountRequest {
        ConnectTradingAccountRequest {
            venue: None,
            credential_ids: None,
            external_trading_account_id: None,
            dealer_account_id: None,
            nickname: None,
        }
    }
}
