/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContingencyType : Order list contingency type
/// Order list contingency type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContingencyType {
    #[serde(rename = "OCO")]
    Oco,
    #[serde(rename = "OTO")]
    Oto,
    #[serde(rename = "OTOCO")]
    Otoco,
}

impl std::fmt::Display for ContingencyType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Oco => write!(f, "OCO"),
            Self::Oto => write!(f, "OTO"),
            Self::Otoco => write!(f, "OTOCO"),
        }
    }
}

impl Default for ContingencyType {
    fn default() -> ContingencyType {
        Self::Oco
    }
}
