/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CredentialType : Type of API credential
/// Type of API credential
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CredentialType {
    #[serde(rename = "API_KEY")]
    ApiKey,
    #[serde(rename = "TOKEN")]
    Token,
    #[serde(rename = "HMAC")]
    Hmac,
    #[serde(rename = "OAUTH")]
    Oauth,
    #[serde(rename = "RSA")]
    Rsa,
    #[serde(rename = "ED25519")]
    Ed25519,
}

impl std::fmt::Display for CredentialType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ApiKey => write!(f, "API_KEY"),
            Self::Token => write!(f, "TOKEN"),
            Self::Hmac => write!(f, "HMAC"),
            Self::Oauth => write!(f, "OAUTH"),
            Self::Rsa => write!(f, "RSA"),
            Self::Ed25519 => write!(f, "ED25519"),
        }
    }
}

impl Default for CredentialType {
    fn default() -> CredentialType {
        Self::ApiKey
    }
}
