/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteMarketSecurityRequest {
    /// Security ID in the format of venue:symbol
    #[serde(rename = "securityId")]
    pub security_id: String,
}

impl DeleteMarketSecurityRequest {
    pub fn new(security_id: String) -> DeleteMarketSecurityRequest {
        DeleteMarketSecurityRequest { security_id }
    }
}
