/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FermataTransferWalletRequest : Transfer assets between wallets owned by the same user
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FermataTransferWalletRequest {
    /// UUID string
    #[serde(rename = "sourceWalletId")]
    pub source_wallet_id: uuid::Uuid,
    /// UUID string
    #[serde(rename = "destWalletId")]
    pub dest_wallet_id: uuid::Uuid,
    /// Asset to transfer
    #[serde(rename = "asset")]
    pub asset: String,
    /// Positive decimal value as string
    #[serde(rename = "amount")]
    pub amount: String,
}

impl FermataTransferWalletRequest {
    /// Transfer assets between wallets owned by the same user
    pub fn new(
        source_wallet_id: uuid::Uuid,
        dest_wallet_id: uuid::Uuid,
        asset: String,
        amount: String,
    ) -> FermataTransferWalletRequest {
        FermataTransferWalletRequest {
            source_wallet_id,
            dest_wallet_id,
            asset,
            amount,
        }
    }
}
