/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FermataPauseDealerRequest : Pause a dealer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FermataPauseDealerRequest {
    /// UUID string
    #[serde(rename = "dealerAccountId")]
    pub dealer_account_id: uuid::Uuid,
}

impl FermataPauseDealerRequest {
    /// Pause a dealer
    pub fn new(dealer_account_id: uuid::Uuid) -> FermataPauseDealerRequest {
        FermataPauseDealerRequest { dealer_account_id }
    }
}
