/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FermataDealer : Fermata dealer entity — a principal trading counterparty in the Fermata venue
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FermataDealer {
    /// UUID string
    #[serde(rename = "dealerAccountId")]
    pub dealer_account_id: uuid::Uuid,
    /// Human-readable dealer name
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "status")]
    pub status: models::DealerStatus,
    /// Base currencies the dealer settles in
    #[serde(rename = "baseCurrencies")]
    pub base_currencies: Vec<String>,
    /// Positive decimal value as string
    #[serde(rename = "riskThreshold", skip_serializing_if = "Option::is_none")]
    pub risk_threshold: Option<String>,
    /// Trading account IDs of exchange accounts linked as liquidity providers
    #[serde(rename = "linkedAccountIds", skip_serializing_if = "Option::is_none")]
    pub linked_account_ids: Option<Vec<uuid::Uuid>>,
    /// Additional dealer configuration (spreads, fees, etc.)
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "createdAt")]
    pub created_at: i64,
    /// Creation timestamp in ISO 8601 format
    #[serde(rename = "createdAtDateTime", skip_serializing_if = "Option::is_none")]
    pub created_at_date_time: Option<String>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "updatedAt")]
    pub updated_at: i64,
    /// Last update timestamp in ISO 8601 format
    #[serde(rename = "updatedAtDateTime", skip_serializing_if = "Option::is_none")]
    pub updated_at_date_time: Option<String>,
}

impl FermataDealer {
    /// Fermata dealer entity — a principal trading counterparty in the Fermata venue
    pub fn new(
        dealer_account_id: uuid::Uuid,
        name: String,
        status: models::DealerStatus,
        base_currencies: Vec<String>,
        created_at: i64,
        updated_at: i64,
    ) -> FermataDealer {
        FermataDealer {
            dealer_account_id,
            name,
            status,
            base_currencies,
            risk_threshold: None,
            linked_account_ids: None,
            config: None,
            created_at,
            created_at_date_time: None,
            updated_at,
            updated_at_date_time: None,
        }
    }
}
