/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FermataCreateWalletRequest : Create a new wallet
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FermataCreateWalletRequest {
    /// Nickname for the new wallet
    #[serde(rename = "nickname", skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
}

impl FermataCreateWalletRequest {
    /// Create a new wallet
    pub fn new() -> FermataCreateWalletRequest {
        FermataCreateWalletRequest { nickname: None }
    }
}
