/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FermataCreateDealerRequest : Create a new dealer in the Fermata venue
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FermataCreateDealerRequest {
    /// Human-readable dealer name
    #[serde(rename = "name")]
    pub name: String,
    /// Base currencies the dealer settles in
    #[serde(rename = "baseCurrencies")]
    pub base_currencies: Vec<String>,
    /// Positive decimal value as string
    #[serde(rename = "riskThreshold", skip_serializing_if = "Option::is_none")]
    pub risk_threshold: Option<String>,
    /// Additional dealer configuration
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl FermataCreateDealerRequest {
    /// Create a new dealer in the Fermata venue
    pub fn new(name: String, base_currencies: Vec<String>) -> FermataCreateDealerRequest {
        FermataCreateDealerRequest {
            name,
            base_currencies,
            risk_threshold: None,
            config: None,
        }
    }
}
