/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FermataFreezeWalletRequest {
    /// UUID string
    #[serde(rename = "walletId")]
    pub wallet_id: uuid::Uuid,
}

impl FermataFreezeWalletRequest {
    pub fn new(wallet_id: uuid::Uuid) -> FermataFreezeWalletRequest {
        FermataFreezeWalletRequest { wallet_id }
    }
}
