/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FermataLinkDealerRequest : Link an exchange trading account to a dealer as a liquidity provider
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FermataLinkDealerRequest {
    /// UUID string
    #[serde(rename = "dealerAccountId")]
    pub dealer_account_id: uuid::Uuid,
    /// UUID string
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
}

impl FermataLinkDealerRequest {
    /// Link an exchange trading account to a dealer as a liquidity provider
    pub fn new(
        dealer_account_id: uuid::Uuid,
        trading_account_id: uuid::Uuid,
    ) -> FermataLinkDealerRequest {
        FermataLinkDealerRequest {
            dealer_account_id,
            trading_account_id,
        }
    }
}
