/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FermataUnlinkDealerRequest : Unlink an exchange trading account from a dealer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FermataUnlinkDealerRequest {
    /// UUID string
    #[serde(rename = "dealerAccountId")]
    pub dealer_account_id: uuid::Uuid,
    /// Internal trading account ID (UUID)
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
}

impl FermataUnlinkDealerRequest {
    /// Unlink an exchange trading account from a dealer
    pub fn new(
        dealer_account_id: uuid::Uuid,
        trading_account_id: uuid::Uuid,
    ) -> FermataUnlinkDealerRequest {
        FermataUnlinkDealerRequest {
            dealer_account_id,
            trading_account_id,
        }
    }
}
