/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FinancialSecurity {
    /// Security ID, id in the format of venue:symbol
    #[serde(rename = "securityId", skip_serializing_if = "Option::is_none")]
    pub security_id: Option<String>,
    /// Symbol
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<models::Venue>,
    #[serde(rename = "securityType", skip_serializing_if = "Option::is_none")]
    pub security_type: Option<models::SecurityType>,
    /// Precision
    #[serde(rename = "precision", skip_serializing_if = "Option::is_none")]
    pub precision: Option<i32>,
    /// Scale
    #[serde(rename = "scale", skip_serializing_if = "Option::is_none")]
    pub scale: Option<i32>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "minQuantity", skip_serializing_if = "Option::is_none")]
    pub min_quantity: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "lotSize", skip_serializing_if = "Option::is_none")]
    pub lot_size: Option<String>,
}

impl FinancialSecurity {
    pub fn new() -> FinancialSecurity {
        FinancialSecurity {
            security_id: None,
            symbol: None,
            venue: None,
            security_type: None,
            precision: None,
            scale: None,
            min_quantity: None,
            lot_size: None,
        }
    }
}
