/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Health200Response {
    #[serde(rename = "status")]
    pub status: models::HealthStatus,
    /// Health check timestamp in milliseconds
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    /// Health check timestamp in ISO 8601 format
    #[serde(rename = "isoDateTime", skip_serializing_if = "Option::is_none")]
    pub iso_date_time: Option<String>,
    /// API version
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "checks", skip_serializing_if = "Option::is_none")]
    pub checks: Option<Box<models::Health200ResponseChecks>>,
}

impl Health200Response {
    pub fn new(status: models::HealthStatus, timestamp: i64, version: String) -> Health200Response {
        Health200Response {
            status,
            timestamp,
            iso_date_time: None,
            version,
            checks: None,
        }
    }
}

