/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Health200ResponseChecks : Health status of individual components
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Health200ResponseChecks {
    #[serde(rename = "database", skip_serializing_if = "Option::is_none")]
    pub database: Option<Box<models::HealthCheckComponent>>,
    #[serde(rename = "temporal", skip_serializing_if = "Option::is_none")]
    pub temporal: Option<Box<models::HealthCheckComponent>>,
    #[serde(rename = "redis", skip_serializing_if = "Option::is_none")]
    pub redis: Option<Box<models::HealthCheckComponent>>,
}

impl Health200ResponseChecks {
    /// Health status of individual components
    pub fn new() -> Health200ResponseChecks {
        Health200ResponseChecks {
            database: None,
            temporal: None,
            redis: None,
        }
    }
}
