/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Instrument {
    /// Instrument ID in format {VENUE}:{BASE}/{QUOTE}
    #[serde(rename = "instrumentId")]
    pub instrument_id: String,
    #[serde(rename = "venue")]
    pub venue: models::Venue,
    /// Human-readable symbol format
    #[serde(rename = "symbol")]
    pub symbol: String,
    /// Symbol format used by the exchange
    #[serde(rename = "externalSymbol")]
    pub external_symbol: String,
    /// Symbol description, human readable description of the instrument
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "instrumentType")]
    pub instrument_type: models::InstrumentType,
    #[serde(rename = "status")]
    pub status: models::InstrumentStatus,
    #[serde(rename = "baseAsset")]
    pub base_asset: String,
    #[serde(rename = "quoteAsset")]
    pub quote_asset: String,
    #[serde(rename = "baseSecurityType", skip_serializing_if = "Option::is_none")]
    pub base_security_type: Option<models::SecurityType>,
    #[serde(rename = "quoteSecurityType", skip_serializing_if = "Option::is_none")]
    pub quote_security_type: Option<models::SecurityType>,
    /// Base asset precision
    #[serde(rename = "basePrecision")]
    pub base_precision: i32,
    /// Quote asset precision
    #[serde(rename = "quotePrecision")]
    pub quote_precision: i32,
    /// Maximum significant digits for base asset
    #[serde(rename = "baseMaxSignificant", deserialize_with = "Option::deserialize")]
    pub base_max_significant: Option<i32>,
    /// Maximum significant digits for quote asset
    #[serde(rename = "quoteMaxSignificant", deserialize_with = "Option::deserialize")]
    pub quote_max_significant: Option<i32>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "lotSize")]
    pub lot_size: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "pipSize")]
    pub pip_size: String,
    /// Base asset scale factor
    #[serde(rename = "baseScale", deserialize_with = "Option::deserialize")]
    pub base_scale: Option<i32>,
    /// Quote asset scale factor
    #[serde(rename = "quoteScale", deserialize_with = "Option::deserialize")]
    pub quote_scale: Option<i32>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "minQuantity")]
    pub min_quantity: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "maxQuantity")]
    pub max_quantity: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "minNotional")]
    pub min_notional: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "maxNotional", skip_serializing_if = "Option::is_none")]
    pub max_notional: Option<String>,
    /// Exchange-specific order filters
    #[serde(rename = "orderFilters", skip_serializing_if = "Option::is_none")]
    pub order_filters: Option<serde_json::Value>,
    #[serde(rename = "orderTypes")]
    pub order_types: Vec<models::OrderType>,
    #[serde(rename = "timeInForceOptions")]
    pub time_in_force_options: Vec<models::TimeInForce>,
    /// Trading hours and schedule information
    #[serde(rename = "tradingHours", skip_serializing_if = "Option::is_none")]
    pub trading_hours: Option<serde_json::Value>,
    /// Whether iceberg orders are allowed
    #[serde(rename = "isIcebergAllowed", skip_serializing_if = "Option::is_none")]
    pub is_iceberg_allowed: Option<bool>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "icebergMinQuantity", skip_serializing_if = "Option::is_none")]
    pub iceberg_min_quantity: Option<String>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "deliveryDate", skip_serializing_if = "Option::is_none")]
    pub delivery_date: Option<i64>,
    /// Delivery date in ISO 8601 format for derivatives
    #[serde(rename = "deliveryDateTime", skip_serializing_if = "Option::is_none")]
    pub delivery_date_time: Option<String>,
    /// Exercise style for options
    #[serde(rename = "exerciseStyle", skip_serializing_if = "Option::is_none")]
    pub exercise_style: Option<ExerciseStyle>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "strikePrice", skip_serializing_if = "Option::is_none")]
    pub strike_price: Option<String>,
}

impl Instrument {
    pub fn new(instrument_id: String, venue: models::Venue, symbol: String, external_symbol: String, instrument_type: models::InstrumentType, status: models::InstrumentStatus, base_asset: String, quote_asset: String, base_precision: i32, quote_precision: i32, base_max_significant: Option<i32>, quote_max_significant: Option<i32>, lot_size: String, pip_size: String, base_scale: Option<i32>, quote_scale: Option<i32>, min_quantity: String, max_quantity: String, min_notional: String, order_types: Vec<models::OrderType>, time_in_force_options: Vec<models::TimeInForce>) -> Instrument {
        Instrument {
            instrument_id,
            venue,
            symbol,
            external_symbol,
            description: None,
            instrument_type,
            status,
            base_asset,
            quote_asset,
            base_security_type: None,
            quote_security_type: None,
            base_precision,
            quote_precision,
            base_max_significant,
            quote_max_significant,
            lot_size,
            pip_size,
            base_scale,
            quote_scale,
            min_quantity,
            max_quantity,
            min_notional,
            max_notional: None,
            order_filters: None,
            order_types,
            time_in_force_options,
            trading_hours: None,
            is_iceberg_allowed: None,
            iceberg_min_quantity: None,
            delivery_date: None,
            delivery_date_time: None,
            exercise_style: None,
            strike_price: None,
        }
    }
}
/// Exercise style for options
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExerciseStyle {
    #[serde(rename = "EUROPEAN")]
    European,
    #[serde(rename = "AMERICAN")]
    American,
}

impl Default for ExerciseStyle {
    fn default() -> ExerciseStyle {
        Self::European
    }
}

