/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Kline : Unified kline payload. Used identically in REST responses (`GET /api/v3/market/kline/list`), WebSocket RPC results (`query.kline.list`), and Centrifugo channel publications (`market:kline:{venue}:{symbol}:{interval}`).  Each candle is a fixed-position OHLCV tuple (no `columns` field). REST returns `isClosed: true` for historical-only queries; `isClosed: false` only when the queried range includes the live bar. Streaming surfaces emit `false` while the current bar is forming and `true` when it closes.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Kline {
    /// Instrument ID in format {VENUE}:{BASE}/{QUOTE}
    #[serde(rename = "instrumentId", skip_serializing_if = "Option::is_none")]
    pub instrument_id: Option<String>,
    #[serde(rename = "venue")]
    pub venue: models::Venue,
    /// Trading pair symbol in format {BASE}/{QUOTE}
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "interval")]
    pub interval: models::KlineInterval,
    /// OHLCV tuples ordered ascending by `openTime`.
    #[serde(rename = "candles")]
    pub candles: Vec<Vec<serde_json::Value>>,
    /// Whether the **last** candle in `candles` is finalized. Historical candles before the last are always closed.
    #[serde(rename = "isClosed")]
    pub is_closed: bool,
    /// Unix timestamp in milliseconds
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
}

impl Kline {
    /// Unified kline payload. Used identically in REST responses (`GET /api/v3/market/kline/list`), WebSocket RPC results (`query.kline.list`), and Centrifugo channel publications (`market:kline:{venue}:{symbol}:{interval}`).  Each candle is a fixed-position OHLCV tuple (no `columns` field). REST returns `isClosed: true` for historical-only queries; `isClosed: false` only when the queried range includes the live bar. Streaming surfaces emit `false` while the current bar is forming and `true` when it closes.
    pub fn new(
        venue: models::Venue,
        symbol: String,
        interval: models::KlineInterval,
        candles: Vec<Vec<serde_json::Value>>,
        is_closed: bool,
        timestamp: i64,
    ) -> Kline {
        Kline {
            instrument_id: None,
            venue,
            symbol,
            interval,
            candles,
            is_closed,
            timestamp,
        }
    }
}
