/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// KlineInterval : Kline (candlestick) interval. Not all venues support every interval — refer to the venue's connector for the supported set.
/// Kline (candlestick) interval. Not all venues support every interval — refer to the venue's connector for the supported set.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum KlineInterval {
    #[serde(rename = "1s")]
    SECOND_1,
    #[serde(rename = "1m")]
    MINUTE_1,
    #[serde(rename = "3m")]
    MINUTE_3,
    #[serde(rename = "5m")]
    MINUTE_5,
    #[serde(rename = "15m")]
    MINUTE_15,
    #[serde(rename = "30m")]
    MINUTE_30,
    #[serde(rename = "1h")]
    HOUR_1,
    #[serde(rename = "2h")]
    HOUR_2,
    #[serde(rename = "4h")]
    HOUR_4,
    #[serde(rename = "6h")]
    HOUR_6,
    #[serde(rename = "8h")]
    HOUR_8,
    #[serde(rename = "12h")]
    HOUR_12,
    #[serde(rename = "1d")]
    DAY_1,
    #[serde(rename = "3d")]
    DAY_3,
    #[serde(rename = "1w")]
    WEEK_1,
    #[serde(rename = "1M")]
    MONTH_1,
}

impl std::fmt::Display for KlineInterval {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SECOND_1 => write!(f, "1s"),
            Self::MINUTE_1 => write!(f, "1m"),
            Self::MINUTE_3 => write!(f, "3m"),
            Self::MINUTE_5 => write!(f, "5m"),
            Self::MINUTE_15 => write!(f, "15m"),
            Self::MINUTE_30 => write!(f, "30m"),
            Self::HOUR_1 => write!(f, "1h"),
            Self::HOUR_2 => write!(f, "2h"),
            Self::HOUR_4 => write!(f, "4h"),
            Self::HOUR_6 => write!(f, "6h"),
            Self::HOUR_8 => write!(f, "8h"),
            Self::HOUR_12 => write!(f, "12h"),
            Self::DAY_1 => write!(f, "1d"),
            Self::DAY_3 => write!(f, "3d"),
            Self::WEEK_1 => write!(f, "1w"),
            Self::MONTH_1 => write!(f, "1M"),
        }
    }
}

impl Default for KlineInterval {
    fn default() -> KlineInterval {
        Self::SECOND_1
    }
}
