/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MarginMode : Margin mode - account-level margin calculation type
/// Margin mode - account-level margin calculation type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MarginMode {
    #[serde(rename = "ISOLATED")]
    Isolated,
    #[serde(rename = "CROSS")]
    Cross,

}

impl std::fmt::Display for MarginMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Isolated => write!(f, "ISOLATED"),
            Self::Cross => write!(f, "CROSS"),
        }
    }
}

impl Default for MarginMode {
    fn default() -> MarginMode {
        Self::Isolated
    }
}

