/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OperationType : Operation type
/// Operation type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OperationType {
    #[serde(rename = "CONNECT")]
    Connect,
    #[serde(rename = "DISCONNECT")]
    Disconnect,
    #[serde(rename = "ENABLE")]
    Enable,
    #[serde(rename = "DISABLE")]
    Disable,
    #[serde(rename = "UPDATE")]
    Update,
    #[serde(rename = "CREDENTIAL_REVOKE")]
    CredentialRevoke,
    #[serde(rename = "CREDENTIAL_ROTATE")]
    CredentialRotate,

}

impl std::fmt::Display for OperationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Connect => write!(f, "CONNECT"),
            Self::Disconnect => write!(f, "DISCONNECT"),
            Self::Enable => write!(f, "ENABLE"),
            Self::Disable => write!(f, "DISABLE"),
            Self::Update => write!(f, "UPDATE"),
            Self::CredentialRevoke => write!(f, "CREDENTIAL_REVOKE"),
            Self::CredentialRotate => write!(f, "CREDENTIAL_ROTATE"),
        }
    }
}

impl Default for OperationType {
    fn default() -> OperationType {
        Self::Connect
    }
}

