/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Orderbook {
    /// Instrument ID in format {VENUE}:{BASE}/{QUOTE}
    #[serde(rename = "instrumentId", skip_serializing_if = "Option::is_none")]
    pub instrument_id: Option<String>,
    #[serde(rename = "venue")]
    pub venue: models::Venue,
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "asks")]
    pub asks: Vec<Vec<String>>,
    #[serde(rename = "bids")]
    pub bids: Vec<Vec<String>>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
}

impl Orderbook {
    pub fn new(venue: models::Venue, symbol: String, asks: Vec<Vec<String>>, bids: Vec<Vec<String>>, timestamp: i64) -> Orderbook {
        Orderbook {
            instrument_id: None,
            venue,
            symbol,
            asks,
            bids,
            timestamp,
        }
    }
}

