/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderBook : Unified order book payload. Used identically in REST responses (`GET /api/v3/market/orderBook/_*`), WebSocket RPC results (`query.orderbook.get` / `query.orderbook.list`), and Centrifugo channel publications (`market:orderbook:{venue}:{symbol}`).  REST `get` and `list` always return `updateType: SNAPSHOT`. Streaming surfaces may emit `SNAPSHOT`, `DIFF`, or `DELTA`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderBook {
    #[serde(rename = "updateType")]
    pub update_type: models::UpdateType,
    /// Instrument ID in format {VENUE}:{BASE}/{QUOTE}
    #[serde(rename = "instrumentId", skip_serializing_if = "Option::is_none")]
    pub instrument_id: Option<String>,
    #[serde(rename = "venue")]
    pub venue: models::Venue,
    /// Trading pair symbol in format {BASE}/{QUOTE}
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "orderBookType")]
    pub order_book_type: models::OrderBookType,
    /// Positional layout of each entry in `bids` / `asks`. Length must equal each row tuple length. Determined by `orderBookType` (e.g. `L2_COUNTED` → `[\"price\", \"quantity\", \"orderCount\"]`).
    #[serde(rename = "columns")]
    pub columns: Vec<String>,
    /// Bid rows (sorted by price descending)
    #[serde(rename = "bids")]
    pub bids: Vec<Vec<String>>,
    /// Ask rows (sorted by price ascending)
    #[serde(rename = "asks")]
    pub asks: Vec<Vec<String>>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
}

impl OrderBook {
    /// Unified order book payload. Used identically in REST responses (`GET /api/v3/market/orderBook/_*`), WebSocket RPC results (`query.orderbook.get` / `query.orderbook.list`), and Centrifugo channel publications (`market:orderbook:{venue}:{symbol}`).  REST `get` and `list` always return `updateType: SNAPSHOT`. Streaming surfaces may emit `SNAPSHOT`, `DIFF`, or `DELTA`.
    pub fn new(
        update_type: models::UpdateType,
        venue: models::Venue,
        symbol: String,
        order_book_type: models::OrderBookType,
        columns: Vec<String>,
        bids: Vec<Vec<String>>,
        asks: Vec<Vec<String>>,
        timestamp: i64,
    ) -> OrderBook {
        OrderBook {
            update_type,
            instrument_id: None,
            venue,
            symbol,
            order_book_type,
            columns,
            bids,
            asks,
            timestamp,
        }
    }
}
