/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PortfolioSummary {
    /// UUID string
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
    /// Base currency for the portfolio summary
    #[serde(rename = "currency")]
    pub currency: String,
    /// Leverage multiplier
    #[serde(rename = "leverage", deserialize_with = "Option::deserialize")]
    pub leverage: Option<i32>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "equity")]
    pub equity: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "margin")]
    pub margin: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "marginLoan")]
    pub margin_loan: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "marginUsage")]
    pub margin_usage: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "marginRequirement")]
    pub margin_requirement: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "marginLevel")]
    pub margin_level: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "credit")]
    pub credit: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "riskExposure")]
    pub risk_exposure: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "maxRiskExposure", skip_serializing_if = "Option::is_none")]
    pub max_risk_exposure: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "riskExposureRate", skip_serializing_if = "Option::is_none")]
    pub risk_exposure_rate: Option<String>,
}

impl PortfolioSummary {
    pub fn new(
        trading_account_id: uuid::Uuid,
        currency: String,
        leverage: Option<i32>,
        equity: String,
        margin: String,
        margin_loan: String,
        margin_usage: String,
        margin_requirement: String,
        margin_level: String,
        credit: String,
        risk_exposure: String,
    ) -> PortfolioSummary {
        PortfolioSummary {
            trading_account_id,
            currency,
            leverage,
            equity,
            margin,
            margin_loan,
            margin_usage,
            margin_requirement,
            margin_level,
            credit,
            risk_exposure,
            max_risk_exposure: None,
            risk_exposure_rate: None,
        }
    }
}
