/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Portfolio {
    /// UUID string
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
    #[serde(rename = "venue")]
    pub venue: models::Venue,
    #[serde(rename = "positions")]
    pub positions: Vec<models::PositionEntry>,
    #[serde(rename = "balances")]
    pub balances: Vec<models::BalanceEntry>,
    #[serde(rename = "summary")]
    pub summary: Box<models::PortfolioSummary>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "updatedAt")]
    pub updated_at: i64,
    /// Last update timestamp in ISO 8601 format
    #[serde(rename = "updatedAtDateTime", skip_serializing_if = "Option::is_none")]
    pub updated_at_date_time: Option<String>,
}

impl Portfolio {
    pub fn new(trading_account_id: uuid::Uuid, venue: models::Venue, positions: Vec<models::PositionEntry>, balances: Vec<models::BalanceEntry>, summary: models::PortfolioSummary, updated_at: i64) -> Portfolio {
        Portfolio {
            trading_account_id,
            venue,
            positions,
            balances,
            summary: Box::new(summary),
            updated_at,
            updated_at_date_time: None,
        }
    }
}

