/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PositionEntry {
    /// UUID string
    #[serde(rename = "positionId")]
    pub position_id: uuid::Uuid,
    /// Security symbol
    #[serde(rename = "securitySymbol")]
    pub security_symbol: String,
    /// External position ID from the exchange
    #[serde(
        rename = "externalPositionId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub external_position_id: Option<Option<String>>,
    /// UUID string
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
    /// Instrument ID in format {VENUE}:{BASE}/{QUOTE}
    #[serde(rename = "instrumentId", skip_serializing_if = "Option::is_none")]
    pub instrument_id: Option<String>,
    #[serde(rename = "securityType")]
    pub security_type: models::SecurityType,
    #[serde(rename = "status")]
    pub status: models::PositionStatus,
    #[serde(rename = "positionSide")]
    pub position_side: models::PositionSide,
    /// Decimal value as string to preserve precision
    #[serde(rename = "quantity")]
    pub quantity: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "entryPrice", skip_serializing_if = "Option::is_none")]
    pub entry_price: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "exitPrice", skip_serializing_if = "Option::is_none")]
    pub exit_price: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "currentPrice", skip_serializing_if = "Option::is_none")]
    pub current_price: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "unrealizedPnl", skip_serializing_if = "Option::is_none")]
    pub unrealized_pnl: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "realizedPnl", skip_serializing_if = "Option::is_none")]
    pub realized_pnl: Option<String>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "createdAt")]
    pub created_at: i64,
    /// Creation timestamp in ISO 8601 format
    #[serde(rename = "createdAtDateTime", skip_serializing_if = "Option::is_none")]
    pub created_at_date_time: Option<String>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "updatedAt")]
    pub updated_at: i64,
    /// Last update timestamp in ISO 8601 format
    #[serde(rename = "updatedAtDateTime", skip_serializing_if = "Option::is_none")]
    pub updated_at_date_time: Option<String>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "closedAt", skip_serializing_if = "Option::is_none")]
    pub closed_at: Option<i64>,
    /// Position closure timestamp in ISO 8601 format
    #[serde(
        rename = "closedAtDateTime",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub closed_at_date_time: Option<Option<String>>,
}

impl PositionEntry {
    pub fn new(
        position_id: uuid::Uuid,
        security_symbol: String,
        trading_account_id: uuid::Uuid,
        security_type: models::SecurityType,
        status: models::PositionStatus,
        position_side: models::PositionSide,
        quantity: String,
        created_at: i64,
        updated_at: i64,
    ) -> PositionEntry {
        PositionEntry {
            position_id,
            security_symbol,
            external_position_id: None,
            trading_account_id,
            instrument_id: None,
            security_type,
            status,
            position_side,
            quantity,
            entry_price: None,
            exit_price: None,
            current_price: None,
            unrealized_pnl: None,
            realized_pnl: None,
            created_at,
            created_at_date_time: None,
            updated_at,
            updated_at_date_time: None,
            closed_at: None,
            closed_at_date_time: None,
        }
    }
}
