/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PositionMode : Position mode setting - how positions are handled
/// Position mode setting - how positions are handled
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PositionMode {
    #[serde(rename = "HEDGE")]
    Hedge,
    #[serde(rename = "NETTING")]
    Netting,

}

impl std::fmt::Display for PositionMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Hedge => write!(f, "HEDGE"),
            Self::Netting => write!(f, "NETTING"),
        }
    }
}

impl Default for PositionMode {
    fn default() -> PositionMode {
        Self::Hedge
    }
}

