/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuantityType : How order quantity is specified
/// How order quantity is specified
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum QuantityType {
    #[serde(rename = "BASE")]
    Base,
    #[serde(rename = "QUOTE")]
    Quote,
    #[serde(rename = "POSITION_RATIO")]
    PositionRatio,
    #[serde(rename = "POSITION_PERCENTAGE")]
    PositionPercentage,
}

impl std::fmt::Display for QuantityType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Base => write!(f, "BASE"),
            Self::Quote => write!(f, "QUOTE"),
            Self::PositionRatio => write!(f, "POSITION_RATIO"),
            Self::PositionPercentage => write!(f, "POSITION_PERCENTAGE"),
        }
    }
}

impl Default for QuantityType {
    fn default() -> QuantityType {
        Self::Base
    }
}
