/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuantityRounding : Quantity rounding strategy to meet lot size requirements. Empty string means no rounding.
/// Quantity rounding strategy to meet lot size requirements. Empty string means no rounding.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum QuantityRounding {
    #[serde(rename = "")]
    Empty,
    #[serde(rename = "UP")]
    Up,
    #[serde(rename = "DOWN")]
    Down,
    #[serde(rename = "NEAREST")]
    Nearest,
    #[serde(rename = "CEIL")]
    Ceil,
    #[serde(rename = "FLOOR")]
    Floor,
    #[serde(rename = "HALF_UP")]
    HalfUp,
    #[serde(rename = "HALF_DOWN")]
    HalfDown,
    #[serde(rename = "HALF_EVEN")]
    HalfEven,
}

impl std::fmt::Display for QuantityRounding {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Empty => write!(f, ""),
            Self::Up => write!(f, "UP"),
            Self::Down => write!(f, "DOWN"),
            Self::Nearest => write!(f, "NEAREST"),
            Self::Ceil => write!(f, "CEIL"),
            Self::Floor => write!(f, "FLOOR"),
            Self::HalfUp => write!(f, "HALF_UP"),
            Self::HalfDown => write!(f, "HALF_DOWN"),
            Self::HalfEven => write!(f, "HALF_EVEN"),
        }
    }
}

impl Default for QuantityRounding {
    fn default() -> QuantityRounding {
        Self::Empty
    }
}
