/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuoteRfqRequest : Request a firm quote. Supports any venue with RFQ capability — use instrumentId for venues that identify pairs by ID, or baseAsset/quoteAsset for symbol-based venues.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuoteRfqRequest {
    /// UUID string
    #[serde(rename = "dealerAccountId")]
    pub dealer_account_id: uuid::Uuid,
    /// UUID string
    #[serde(rename = "traderAccountId", skip_serializing_if = "Option::is_none")]
    pub trader_account_id: Option<uuid::Uuid>,
    /// Instrument ID in format {VENUE}:{BASE}/{QUOTE}
    #[serde(rename = "instrumentId", skip_serializing_if = "Option::is_none")]
    pub instrument_id: Option<String>,
    /// Base asset to trade. Used with quoteAsset for symbol-based venues.
    #[serde(rename = "baseAsset", skip_serializing_if = "Option::is_none")]
    pub base_asset: Option<String>,
    /// Quote asset (payment currency). Used with baseAsset for symbol-based venues.
    #[serde(rename = "quoteAsset", skip_serializing_if = "Option::is_none")]
    pub quote_asset: Option<String>,
    #[serde(rename = "orderSide")]
    pub order_side: models::OrderSide,
    /// Positive decimal value as string
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<String>,
    /// Positive decimal value as string
    #[serde(rename = "quoteQuantity", skip_serializing_if = "Option::is_none")]
    pub quote_quantity: Option<String>,
    /// Client-provided reference for idempotency and tracking
    #[serde(rename = "quoteRequestId", skip_serializing_if = "Option::is_none")]
    pub quote_request_id: Option<String>,
    /// Time to live in seconds
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i32>,
    /// Absolute expiry timestamp (ISO 8601). Mutually exclusive with ttl. If neither ttl nor expireAt is set, defaults to 10 seconds from quote creation.
    #[serde(rename = "expireAt", skip_serializing_if = "Option::is_none")]
    pub expire_at: Option<String>,
    /// UUID string
    #[serde(rename = "pricingProfileId", skip_serializing_if = "Option::is_none")]
    pub pricing_profile_id: Option<uuid::Uuid>,
}

impl QuoteRfqRequest {
    /// Request a firm quote. Supports any venue with RFQ capability — use instrumentId for venues that identify pairs by ID, or baseAsset/quoteAsset for symbol-based venues.
    pub fn new(dealer_account_id: uuid::Uuid, order_side: models::OrderSide) -> QuoteRfqRequest {
        QuoteRfqRequest {
            dealer_account_id,
            trader_account_id: None,
            instrument_id: None,
            base_asset: None,
            quote_asset: None,
            order_side,
            quantity: None,
            quote_quantity: None,
            quote_request_id: None,
            ttl: None,
            expire_at: None,
            pricing_profile_id: None,
        }
    }
}
