/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Quote : RFQ quote — a bilateral contract between the user and the dealer with a guaranteed execution price
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Quote {
    /// UUID string
    #[serde(rename = "quoteId")]
    pub quote_id: uuid::Uuid,
    /// Client-provided reference for idempotency and tracking
    #[serde(rename = "quoteRequestId", skip_serializing_if = "Option::is_none")]
    pub quote_request_id: Option<String>,
    /// External quote identifier from upstream venue
    #[serde(rename = "externalQuoteId", skip_serializing_if = "Option::is_none")]
    pub external_quote_id: Option<String>,
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<models::Venue>,
    /// Instrument ID in format {VENUE}:{BASE}/{QUOTE}
    #[serde(rename = "instrumentId", skip_serializing_if = "Option::is_none")]
    pub instrument_id: Option<String>,
    /// UUID string
    #[serde(rename = "dealerAccountId")]
    pub dealer_account_id: uuid::Uuid,
    /// UUID string
    #[serde(rename = "traderAccountId", skip_serializing_if = "Option::is_none")]
    pub trader_account_id: Option<uuid::Uuid>,
    /// Base asset being traded
    #[serde(rename = "baseAsset")]
    pub base_asset: String,
    /// Quote asset (payment currency)
    #[serde(rename = "quoteAsset")]
    pub quote_asset: String,
    #[serde(rename = "orderSide")]
    pub order_side: models::OrderSide,
    #[serde(rename = "quantityType", skip_serializing_if = "Option::is_none")]
    pub quantity_type: Option<models::QuantityType>,
    /// Positive decimal value as string
    #[serde(rename = "quantity")]
    pub quantity: String,
    /// Positive decimal value as string
    #[serde(rename = "quoteQuantity")]
    pub quote_quantity: String,
    /// Positive decimal value as string
    #[serde(rename = "price")]
    pub price: String,
    #[serde(rename = "status")]
    pub status: models::QuoteStatus,
    /// Reason for quote rejection, if status is REJECTED
    #[serde(rename = "rejectReason", skip_serializing_if = "Option::is_none")]
    pub reject_reason: Option<String>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "createdAt")]
    pub created_at: i64,
    /// Quote creation timestamp in ISO 8601 format
    #[serde(rename = "createdAtDateTime", skip_serializing_if = "Option::is_none")]
    pub created_at_date_time: Option<String>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    /// Last update timestamp in ISO 8601 format
    #[serde(rename = "updatedAtDateTime", skip_serializing_if = "Option::is_none")]
    pub updated_at_date_time: Option<String>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "expireAt")]
    pub expire_at: i64,
    /// Quote expiration timestamp in ISO 8601 format
    #[serde(rename = "expireAtDateTime", skip_serializing_if = "Option::is_none")]
    pub expire_at_date_time: Option<String>,
    /// UUID string
    #[serde(rename = "pricingProfileId", skip_serializing_if = "Option::is_none")]
    pub pricing_profile_id: Option<uuid::Uuid>,
}

impl Quote {
    /// RFQ quote — a bilateral contract between the user and the dealer with a guaranteed execution price
    pub fn new(
        quote_id: uuid::Uuid,
        dealer_account_id: uuid::Uuid,
        base_asset: String,
        quote_asset: String,
        order_side: models::OrderSide,
        quantity: String,
        quote_quantity: String,
        price: String,
        status: models::QuoteStatus,
        created_at: i64,
        expire_at: i64,
    ) -> Quote {
        Quote {
            quote_id,
            quote_request_id: None,
            external_quote_id: None,
            venue: None,
            instrument_id: None,
            dealer_account_id,
            trader_account_id: None,
            base_asset,
            quote_asset,
            order_side,
            quantity_type: None,
            quantity,
            quote_quantity,
            price,
            status,
            reject_reason: None,
            created_at,
            created_at_date_time: None,
            updated_at: None,
            updated_at_date_time: None,
            expire_at,
            expire_at_date_time: None,
            pricing_profile_id: None,
        }
    }
}
