/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseError {
    /// Error code
    #[serde(rename = "code")]
    pub code: String,
    /// Error message
    #[serde(rename = "message")]
    pub message: String,
}

impl ResponseError {
    pub fn new(code: String, message: String) -> ResponseError {
        ResponseError { code, message }
    }
}
