/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RevokeTradingAccountCredentialRequest {
    /// UUID string
    #[serde(rename = "credentialId")]
    pub credential_id: uuid::Uuid,
}

impl RevokeTradingAccountCredentialRequest {
    pub fn new(credential_id: uuid::Uuid) -> RevokeTradingAccountCredentialRequest {
        RevokeTradingAccountCredentialRequest { credential_id }
    }
}
