/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RotateTradingAccountCredentialRequest {
    /// UUID string
    #[serde(rename = "credentialId")]
    pub credential_id: uuid::Uuid,
    #[serde(rename = "apiKey", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    #[serde(rename = "apiSecret", skip_serializing_if = "Option::is_none")]
    pub api_secret: Option<String>,
    #[serde(rename = "apiPassphrase", skip_serializing_if = "Option::is_none")]
    pub api_passphrase: Option<String>,
}

impl RotateTradingAccountCredentialRequest {
    pub fn new(credential_id: uuid::Uuid) -> RotateTradingAccountCredentialRequest {
        RotateTradingAccountCredentialRequest {
            credential_id,
            api_key: None,
            api_secret: None,
            api_passphrase: None,
        }
    }
}
