/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcSaveTradeOrderParams : Request to save a trade order
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcSaveTradeOrderParams {
    #[serde(rename = "tradeOrder")]
    pub trade_order: Box<models::RpcTradeOrder>,
}

impl RpcSaveTradeOrderParams {
    /// Request to save a trade order
    pub fn new(trade_order: models::RpcTradeOrder) -> RpcSaveTradeOrderParams {
        RpcSaveTradeOrderParams {
            trade_order: Box::new(trade_order),
        }
    }
}
