/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcError : RPC error response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcError {
    /// Error code (non-zero indicates error). Format: AABBB where AA is the module code and BBB is the error code
    #[serde(rename = "code")]
    pub code: i32,
    /// Error message
    #[serde(rename = "message")]
    pub message: String,
    /// Whether the error is temporary and retryable
    #[serde(rename = "temporary", skip_serializing_if = "Option::is_none")]
    pub temporary: Option<bool>,
}

impl RpcError {
    /// RPC error response
    pub fn new(code: i32, message: String) -> RpcError {
        RpcError {
            code,
            message,
            temporary: None,
        }
    }
}
