/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcTicker : Market ticker data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcTicker {
    #[serde(rename = "instrumentId", skip_serializing_if = "Option::is_none")]
    pub instrument_id: Option<String>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "exchange", skip_serializing_if = "Option::is_none")]
    pub exchange: Option<String>,
    #[serde(rename = "exchangeTime", skip_serializing_if = "Option::is_none")]
    pub exchange_time: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    /// Ask price (decimal)
    #[serde(rename = "ask", skip_serializing_if = "Option::is_none")]
    pub ask: Option<String>,
    /// Ask quantity (decimal)
    #[serde(rename = "askQuantity", skip_serializing_if = "Option::is_none")]
    pub ask_quantity: Option<String>,
    /// Bid price (decimal)
    #[serde(rename = "bid", skip_serializing_if = "Option::is_none")]
    pub bid: Option<String>,
    /// Bid quantity (decimal)
    #[serde(rename = "bidQuantity", skip_serializing_if = "Option::is_none")]
    pub bid_quantity: Option<String>,
    /// Last price (decimal)
    #[serde(rename = "last", skip_serializing_if = "Option::is_none")]
    pub last: Option<String>,
    /// Last quantity (decimal)
    #[serde(rename = "lastQuantity", skip_serializing_if = "Option::is_none")]
    pub last_quantity: Option<String>,
}

impl RpcTicker {
    /// Market ticker data
    pub fn new() -> RpcTicker {
        RpcTicker {
            instrument_id: None,
            symbol: None,
            exchange: None,
            exchange_time: None,
            time: None,
            ask: None,
            ask_quantity: None,
            bid: None,
            bid_quantity: None,
            last: None,
            last_quantity: None,
        }
    }
}

