/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcSaveTickersParams : Request to save tickers
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcSaveTickersParams {
    #[serde(rename = "tickers")]
    pub tickers: Vec<models::RpcTicker>,
}

impl RpcSaveTickersParams {
    /// Request to save tickers
    pub fn new(tickers: Vec<models::RpcTicker>) -> RpcSaveTickersParams {
        RpcSaveTickersParams { tickers }
    }
}
