/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcSaveInstrumentsParams : Request to save instruments
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcSaveInstrumentsParams {
    #[serde(rename = "instruments")]
    pub instruments: Vec<models::RpcInstrument>,
}

impl RpcSaveInstrumentsParams {
    /// Request to save instruments
    pub fn new(instruments: Vec<models::RpcInstrument>) -> RpcSaveInstrumentsParams {
        RpcSaveInstrumentsParams { instruments }
    }
}
