/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcValidateTradingAccountParams : Request to validate a trading account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcValidateTradingAccountParams {
    #[serde(rename = "tradingAccount")]
    pub trading_account: Box<models::RpcTradingAccount>,
}

impl RpcValidateTradingAccountParams {
    /// Request to validate a trading account
    pub fn new(trading_account: models::RpcTradingAccount) -> RpcValidateTradingAccountParams {
        RpcValidateTradingAccountParams {
            trading_account: Box::new(trading_account),
        }
    }
}
