/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcSecurityUpdatedEvent : Security update event (pushed via WebSocket)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcSecurityUpdatedEvent {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::RpcSecurity>>,
}

impl RpcSecurityUpdatedEvent {
    /// Security update event (pushed via WebSocket)
    pub fn new() -> RpcSecurityUpdatedEvent {
        RpcSecurityUpdatedEvent { data: None }
    }
}
