/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcTradingAccountCredential : Trading account credential
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcTradingAccountCredential {
    #[serde(rename = "credentialId", skip_serializing_if = "Option::is_none")]
    pub credential_id: Option<uuid::Uuid>,
    #[serde(rename = "nickname", skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
    #[serde(
        rename = "credentialType",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub credential_type: Option<Option<models::CredentialType>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::CredentialStatus>,
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<models::Venue>,
    /// API key (only in responses where withSecret=true)
    #[serde(rename = "apiKey", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "revokedAt", skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<String>,
    /// Whether metadata fields are populated
    #[serde(rename = "withInfo", skip_serializing_if = "Option::is_none")]
    pub with_info: Option<bool>,
    /// Whether secret fields are populated
    #[serde(rename = "withSecret", skip_serializing_if = "Option::is_none")]
    pub with_secret: Option<bool>,
}

impl RpcTradingAccountCredential {
    /// Trading account credential
    pub fn new() -> RpcTradingAccountCredential {
        RpcTradingAccountCredential {
            credential_id: None,
            nickname: None,
            credential_type: None,
            status: None,
            venue: None,
            api_key: None,
            created_at: None,
            updated_at: None,
            revoked_at: None,
            with_info: None,
            with_secret: None,
        }
    }
}
