/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcGetOrderBookParams : Request to get order book for an instrument
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcGetOrderBookParams {
    /// Instrument ID (e.g., BINANCE:BTC/USDT)
    #[serde(rename = "instrumentId", skip_serializing_if = "Option::is_none")]
    pub instrument_id: Option<String>,
    /// Venue (alternative to instrumentId)
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<String>,
    /// Symbol (alternative to instrumentId)
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Order book depth
    #[serde(rename = "depth", skip_serializing_if = "Option::is_none")]
    pub depth: Option<i32>,
}

impl RpcGetOrderBookParams {
    /// Request to get order book for an instrument
    pub fn new() -> RpcGetOrderBookParams {
        RpcGetOrderBookParams {
            instrument_id: None,
            venue: None,
            symbol: None,
            depth: None,
        }
    }
}
