/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcSaveKlinesParams : Request to save klines (candlestick data)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcSaveKlinesParams {
    #[serde(rename = "klines")]
    pub klines: Vec<models::RpcKline>,
}

impl RpcSaveKlinesParams {
    /// Request to save klines (candlestick data)
    pub fn new(klines: Vec<models::RpcKline>) -> RpcSaveKlinesParams {
        RpcSaveKlinesParams {
            klines,
        }
    }
}

