/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcSyncSecuritiesParams : Request to sync securities from venue
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcSyncSecuritiesParams {
    #[serde(rename = "venue")]
    pub venue: models::Venue,
    #[serde(rename = "securities", skip_serializing_if = "Option::is_none")]
    pub securities: Option<Vec<String>>,
}

impl RpcSyncSecuritiesParams {
    /// Request to sync securities from venue
    pub fn new(venue: models::Venue) -> RpcSyncSecuritiesParams {
        RpcSyncSecuritiesParams {
            venue,
            securities: None,
        }
    }
}

