/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcMethod : RPC method name corresponding to event types in the system. Format: `{category}.{resource}.{action}` - `command.*` - Actions that modify state - `query.*` - Actions that read state - `response.*` - Server responses (used internally) - `event.*` - Push notifications for state changes
/// RPC method name corresponding to event types in the system. Format: `{category}.{resource}.{action}` - `command.*` - Actions that modify state - `query.*` - Actions that read state - `response.*` - Server responses (used internally) - `event.*` - Push notifications for state changes
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RpcMethod {
    #[serde(rename = "query.system.info")]
    QuerySystemInfo,
    #[serde(rename = "response.system.info")]
    ResponseSystemInfo,
    #[serde(rename = "query.system.check")]
    QuerySystemCheck,
    #[serde(rename = "response.system.check")]
    ResponseSystemCheck,
    #[serde(rename = "command.trading_account.create")]
    CommandTradingAccountCreate,
    #[serde(rename = "response.trading_account.create")]
    ResponseTradingAccountCreate,
    #[serde(rename = "command.trading_account.save")]
    CommandTradingAccountSave,
    #[serde(rename = "response.trading_account.save")]
    ResponseTradingAccountSave,
    #[serde(rename = "command.trading_account.delete")]
    CommandTradingAccountDelete,
    #[serde(rename = "response.trading_account.delete")]
    ResponseTradingAccountDelete,
    #[serde(rename = "command.trading_account.update")]
    CommandTradingAccountUpdate,
    #[serde(rename = "response.trading_account.update")]
    ResponseTradingAccountUpdate,
    #[serde(rename = "command.trading_account.validate")]
    CommandTradingAccountValidate,
    #[serde(rename = "response.trading_account.validate")]
    ResponseTradingAccountValidate,
    #[serde(rename = "command.trading_account.connect")]
    CommandTradingAccountConnect,
    #[serde(rename = "response.trading_account.connect")]
    ResponseTradingAccountConnect,
    #[serde(rename = "command.trading_account.disconnect")]
    CommandTradingAccountDisconnect,
    #[serde(rename = "response.trading_account.disconnect")]
    ResponseTradingAccountDisconnect,
    #[serde(rename = "command.trading_account.enable")]
    CommandTradingAccountEnable,
    #[serde(rename = "response.trading_account.enable")]
    ResponseTradingAccountEnable,
    #[serde(rename = "command.trading_account.disable")]
    CommandTradingAccountDisable,
    #[serde(rename = "response.trading_account.disable")]
    ResponseTradingAccountDisable,
    #[serde(rename = "query.trading_account.list")]
    QueryTradingAccountList,
    #[serde(rename = "response.trading_account.list")]
    ResponseTradingAccountList,
    #[serde(rename = "query.trading_account.operation.list")]
    QueryTradingAccountOperationList,
    #[serde(rename = "response.trading_account.operation.list")]
    ResponseTradingAccountOperationList,
    #[serde(rename = "event.trading_account.updated")]
    EventTradingAccountUpdated,
    #[serde(rename = "event.trading_account.subscription.updated")]
    EventTradingAccountSubscriptionUpdated,
    #[serde(rename = "command.trading_account.subscribe")]
    CommandTradingAccountSubscribe,
    #[serde(rename = "response.trading_account.subscribe")]
    ResponseTradingAccountSubscribe,
    #[serde(rename = "command.trading_account.unsubscribe")]
    CommandTradingAccountUnsubscribe,
    #[serde(rename = "response.trading_account.unsubscribe")]
    ResponseTradingAccountUnsubscribe,
    #[serde(rename = "query.trading_account.subscription.list")]
    QueryTradingAccountSubscriptionList,
    #[serde(rename = "response.trading_account.subscription.list")]
    ResponseTradingAccountSubscriptionList,
    #[serde(rename = "command.credential.create")]
    CommandCredentialCreate,
    #[serde(rename = "response.credential.create")]
    ResponseCredentialCreate,
    #[serde(rename = "command.credential.save")]
    CommandCredentialSave,
    #[serde(rename = "response.credential.save")]
    ResponseCredentialSave,
    #[serde(rename = "query.credential.list")]
    QueryCredentialList,
    #[serde(rename = "response.credential.list")]
    ResponseCredentialList,
    #[serde(rename = "command.credential.revoke")]
    CommandCredentialRevoke,
    #[serde(rename = "response.credential.revoke")]
    ResponseCredentialRevoke,
    #[serde(rename = "command.credential.rotate")]
    CommandCredentialRotate,
    #[serde(rename = "response.credential.rotate")]
    ResponseCredentialRotate,
    #[serde(rename = "command.credential.verify")]
    CommandCredentialVerify,
    #[serde(rename = "response.credential.verify")]
    ResponseCredentialVerify,
    #[serde(rename = "event.credential.updated")]
    EventCredentialUpdated,
    #[serde(rename = "command.trade_order.submit")]
    CommandTradeOrderSubmit,
    #[serde(rename = "response.trade_order.submit")]
    ResponseTradeOrderSubmit,
    #[serde(rename = "command.trade_order.cancel")]
    CommandTradeOrderCancel,
    #[serde(rename = "response.trade_order.cancel")]
    ResponseTradeOrderCancel,
    #[serde(rename = "command.trade_order.save")]
    CommandTradeOrderSave,
    #[serde(rename = "response.trade_order.save")]
    ResponseTradeOrderSave,
    #[serde(rename = "query.trade_order.get")]
    QueryTradeOrderGet,
    #[serde(rename = "response.trade_order.get")]
    ResponseTradeOrderGet,
    #[serde(rename = "query.trade_order.get_by_id")]
    QueryTradeOrderGetById,
    #[serde(rename = "response.trade_order.get_by_id")]
    ResponseTradeOrderGetById,
    #[serde(rename = "query.trade_order.list")]
    QueryTradeOrderList,
    #[serde(rename = "response.trade_order.list")]
    ResponseTradeOrderList,
    #[serde(rename = "event.trade_order.updated")]
    EventTradeOrderUpdated,
    #[serde(rename = "query.portfolio.get")]
    QueryPortfolioGet,
    #[serde(rename = "response.portfolio.get")]
    ResponsePortfolioGet,
    #[serde(rename = "query.portfolio.list")]
    QueryPortfolioList,
    #[serde(rename = "response.portfolio.list")]
    ResponsePortfolioList,
    #[serde(rename = "command.portfolio.save")]
    CommandPortfolioSave,
    #[serde(rename = "response.portfolio.save")]
    ResponsePortfolioSave,
    #[serde(rename = "event.portfolio.updated")]
    EventPortfolioUpdated,
    #[serde(rename = "command.instrument.sync")]
    CommandInstrumentSync,
    #[serde(rename = "response.instrument.sync")]
    ResponseInstrumentSync,
    #[serde(rename = "command.instrument.save")]
    CommandInstrumentSave,
    #[serde(rename = "response.instrument.save")]
    ResponseInstrumentSave,
    #[serde(rename = "query.instrument.list")]
    QueryInstrumentList,
    #[serde(rename = "response.instrument.list")]
    ResponseInstrumentList,
    #[serde(rename = "command.instrument.delete")]
    CommandInstrumentDelete,
    #[serde(rename = "response.instrument.delete")]
    ResponseInstrumentDelete,
    #[serde(rename = "command.instrument.enable")]
    CommandInstrumentEnable,
    #[serde(rename = "response.instrument.enable")]
    ResponseInstrumentEnable,
    #[serde(rename = "command.instrument.disable")]
    CommandInstrumentDisable,
    #[serde(rename = "response.instrument.disable")]
    ResponseInstrumentDisable,
    #[serde(rename = "event.instrument.updated")]
    EventInstrumentUpdated,
    #[serde(rename = "command.security.sync")]
    CommandSecuritySync,
    #[serde(rename = "response.security.sync")]
    ResponseSecuritySync,
    #[serde(rename = "command.security.save")]
    CommandSecuritySave,
    #[serde(rename = "response.security.save")]
    ResponseSecuritySave,
    #[serde(rename = "command.security.delete")]
    CommandSecurityDelete,
    #[serde(rename = "response.security.delete")]
    ResponseSecurityDelete,
    #[serde(rename = "query.security.list")]
    QuerySecurityList,
    #[serde(rename = "response.security.list")]
    ResponseSecurityList,
    #[serde(rename = "event.security.updated")]
    EventSecurityUpdated,
    #[serde(rename = "query.venue.list")]
    QueryVenueList,
    #[serde(rename = "response.venue.list")]
    ResponseVenueList,
    #[serde(rename = "query.orderbook.get")]
    QueryOrderbookGet,
    #[serde(rename = "response.orderbook.get")]
    ResponseOrderbookGet,
    #[serde(rename = "query.orderbook.list")]
    QueryOrderbookList,
    #[serde(rename = "response.orderbook.list")]
    ResponseOrderbookList,
    #[serde(rename = "command.orderbook.save")]
    CommandOrderbookSave,
    #[serde(rename = "response.orderbook.save")]
    ResponseOrderbookSave,
    #[serde(rename = "event.orderbook.updated")]
    EventOrderbookUpdated,
    #[serde(rename = "command.kline.save")]
    CommandKlineSave,
    #[serde(rename = "response.kline.save")]
    ResponseKlineSave,
    #[serde(rename = "query.kline.list")]
    QueryKlineList,
    #[serde(rename = "response.kline.list")]
    ResponseKlineList,
    #[serde(rename = "command.ticker.save")]
    CommandTickerSave,
    #[serde(rename = "response.ticker.save")]
    ResponseTickerSave,
    #[serde(rename = "query.ticker.list")]
    QueryTickerList,
    #[serde(rename = "response.ticker.list")]
    ResponseTickerList,
    #[serde(rename = "command.market.subscription.orderbook.subscribe")]
    CommandMarketSubscriptionOrderbookSubscribe,
    #[serde(rename = "response.market.subscription.orderbook.subscribe")]
    ResponseMarketSubscriptionOrderbookSubscribe,
    #[serde(rename = "command.market.subscription.orderbook.unsubscribe")]
    CommandMarketSubscriptionOrderbookUnsubscribe,
    #[serde(rename = "response.market.subscription.orderbook.unsubscribe")]
    ResponseMarketSubscriptionOrderbookUnsubscribe,
    #[serde(rename = "query.market.subscription.orderbook.list")]
    QueryMarketSubscriptionOrderbookList,
    #[serde(rename = "response.market.subscription.orderbook.list")]
    ResponseMarketSubscriptionOrderbookList,
    #[serde(rename = "command.subscription.create")]
    CommandSubscriptionCreate,
    #[serde(rename = "response.subscription.create")]
    ResponseSubscriptionCreate,
    #[serde(rename = "query.subscription.list")]
    QuerySubscriptionList,
    #[serde(rename = "response.subscription.list")]
    ResponseSubscriptionList,
    #[serde(rename = "event.subscription.updated")]
    EventSubscriptionUpdated,
    #[serde(rename = "command.subscription.mc.create")]
    CommandSubscriptionMcCreate,
    #[serde(rename = "response.subscription.mc.create")]
    ResponseSubscriptionMcCreate,
}

impl std::fmt::Display for RpcMethod {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::QuerySystemInfo => write!(f, "query.system.info"),
            Self::ResponseSystemInfo => write!(f, "response.system.info"),
            Self::QuerySystemCheck => write!(f, "query.system.check"),
            Self::ResponseSystemCheck => write!(f, "response.system.check"),
            Self::CommandTradingAccountCreate => write!(f, "command.trading_account.create"),
            Self::ResponseTradingAccountCreate => write!(f, "response.trading_account.create"),
            Self::CommandTradingAccountSave => write!(f, "command.trading_account.save"),
            Self::ResponseTradingAccountSave => write!(f, "response.trading_account.save"),
            Self::CommandTradingAccountDelete => write!(f, "command.trading_account.delete"),
            Self::ResponseTradingAccountDelete => write!(f, "response.trading_account.delete"),
            Self::CommandTradingAccountUpdate => write!(f, "command.trading_account.update"),
            Self::ResponseTradingAccountUpdate => write!(f, "response.trading_account.update"),
            Self::CommandTradingAccountValidate => write!(f, "command.trading_account.validate"),
            Self::ResponseTradingAccountValidate => write!(f, "response.trading_account.validate"),
            Self::CommandTradingAccountConnect => write!(f, "command.trading_account.connect"),
            Self::ResponseTradingAccountConnect => write!(f, "response.trading_account.connect"),
            Self::CommandTradingAccountDisconnect => {
                write!(f, "command.trading_account.disconnect")
            }
            Self::ResponseTradingAccountDisconnect => {
                write!(f, "response.trading_account.disconnect")
            }
            Self::CommandTradingAccountEnable => write!(f, "command.trading_account.enable"),
            Self::ResponseTradingAccountEnable => write!(f, "response.trading_account.enable"),
            Self::CommandTradingAccountDisable => write!(f, "command.trading_account.disable"),
            Self::ResponseTradingAccountDisable => write!(f, "response.trading_account.disable"),
            Self::QueryTradingAccountList => write!(f, "query.trading_account.list"),
            Self::ResponseTradingAccountList => write!(f, "response.trading_account.list"),
            Self::QueryTradingAccountOperationList => {
                write!(f, "query.trading_account.operation.list")
            }
            Self::ResponseTradingAccountOperationList => {
                write!(f, "response.trading_account.operation.list")
            }
            Self::EventTradingAccountUpdated => write!(f, "event.trading_account.updated"),
            Self::EventTradingAccountSubscriptionUpdated => {
                write!(f, "event.trading_account.subscription.updated")
            }
            Self::CommandTradingAccountSubscribe => write!(f, "command.trading_account.subscribe"),
            Self::ResponseTradingAccountSubscribe => {
                write!(f, "response.trading_account.subscribe")
            }
            Self::CommandTradingAccountUnsubscribe => {
                write!(f, "command.trading_account.unsubscribe")
            }
            Self::ResponseTradingAccountUnsubscribe => {
                write!(f, "response.trading_account.unsubscribe")
            }
            Self::QueryTradingAccountSubscriptionList => {
                write!(f, "query.trading_account.subscription.list")
            }
            Self::ResponseTradingAccountSubscriptionList => {
                write!(f, "response.trading_account.subscription.list")
            }
            Self::CommandCredentialCreate => write!(f, "command.credential.create"),
            Self::ResponseCredentialCreate => write!(f, "response.credential.create"),
            Self::CommandCredentialSave => write!(f, "command.credential.save"),
            Self::ResponseCredentialSave => write!(f, "response.credential.save"),
            Self::QueryCredentialList => write!(f, "query.credential.list"),
            Self::ResponseCredentialList => write!(f, "response.credential.list"),
            Self::CommandCredentialRevoke => write!(f, "command.credential.revoke"),
            Self::ResponseCredentialRevoke => write!(f, "response.credential.revoke"),
            Self::CommandCredentialRotate => write!(f, "command.credential.rotate"),
            Self::ResponseCredentialRotate => write!(f, "response.credential.rotate"),
            Self::CommandCredentialVerify => write!(f, "command.credential.verify"),
            Self::ResponseCredentialVerify => write!(f, "response.credential.verify"),
            Self::EventCredentialUpdated => write!(f, "event.credential.updated"),
            Self::CommandTradeOrderSubmit => write!(f, "command.trade_order.submit"),
            Self::ResponseTradeOrderSubmit => write!(f, "response.trade_order.submit"),
            Self::CommandTradeOrderCancel => write!(f, "command.trade_order.cancel"),
            Self::ResponseTradeOrderCancel => write!(f, "response.trade_order.cancel"),
            Self::CommandTradeOrderSave => write!(f, "command.trade_order.save"),
            Self::ResponseTradeOrderSave => write!(f, "response.trade_order.save"),
            Self::QueryTradeOrderGet => write!(f, "query.trade_order.get"),
            Self::ResponseTradeOrderGet => write!(f, "response.trade_order.get"),
            Self::QueryTradeOrderGetById => write!(f, "query.trade_order.get_by_id"),
            Self::ResponseTradeOrderGetById => write!(f, "response.trade_order.get_by_id"),
            Self::QueryTradeOrderList => write!(f, "query.trade_order.list"),
            Self::ResponseTradeOrderList => write!(f, "response.trade_order.list"),
            Self::EventTradeOrderUpdated => write!(f, "event.trade_order.updated"),
            Self::QueryPortfolioGet => write!(f, "query.portfolio.get"),
            Self::ResponsePortfolioGet => write!(f, "response.portfolio.get"),
            Self::QueryPortfolioList => write!(f, "query.portfolio.list"),
            Self::ResponsePortfolioList => write!(f, "response.portfolio.list"),
            Self::CommandPortfolioSave => write!(f, "command.portfolio.save"),
            Self::ResponsePortfolioSave => write!(f, "response.portfolio.save"),
            Self::EventPortfolioUpdated => write!(f, "event.portfolio.updated"),
            Self::CommandInstrumentSync => write!(f, "command.instrument.sync"),
            Self::ResponseInstrumentSync => write!(f, "response.instrument.sync"),
            Self::CommandInstrumentSave => write!(f, "command.instrument.save"),
            Self::ResponseInstrumentSave => write!(f, "response.instrument.save"),
            Self::QueryInstrumentList => write!(f, "query.instrument.list"),
            Self::ResponseInstrumentList => write!(f, "response.instrument.list"),
            Self::CommandInstrumentDelete => write!(f, "command.instrument.delete"),
            Self::ResponseInstrumentDelete => write!(f, "response.instrument.delete"),
            Self::CommandInstrumentEnable => write!(f, "command.instrument.enable"),
            Self::ResponseInstrumentEnable => write!(f, "response.instrument.enable"),
            Self::CommandInstrumentDisable => write!(f, "command.instrument.disable"),
            Self::ResponseInstrumentDisable => write!(f, "response.instrument.disable"),
            Self::EventInstrumentUpdated => write!(f, "event.instrument.updated"),
            Self::CommandSecuritySync => write!(f, "command.security.sync"),
            Self::ResponseSecuritySync => write!(f, "response.security.sync"),
            Self::CommandSecuritySave => write!(f, "command.security.save"),
            Self::ResponseSecuritySave => write!(f, "response.security.save"),
            Self::CommandSecurityDelete => write!(f, "command.security.delete"),
            Self::ResponseSecurityDelete => write!(f, "response.security.delete"),
            Self::QuerySecurityList => write!(f, "query.security.list"),
            Self::ResponseSecurityList => write!(f, "response.security.list"),
            Self::EventSecurityUpdated => write!(f, "event.security.updated"),
            Self::QueryVenueList => write!(f, "query.venue.list"),
            Self::ResponseVenueList => write!(f, "response.venue.list"),
            Self::QueryOrderbookGet => write!(f, "query.orderbook.get"),
            Self::ResponseOrderbookGet => write!(f, "response.orderbook.get"),
            Self::QueryOrderbookList => write!(f, "query.orderbook.list"),
            Self::ResponseOrderbookList => write!(f, "response.orderbook.list"),
            Self::CommandOrderbookSave => write!(f, "command.orderbook.save"),
            Self::ResponseOrderbookSave => write!(f, "response.orderbook.save"),
            Self::EventOrderbookUpdated => write!(f, "event.orderbook.updated"),
            Self::CommandKlineSave => write!(f, "command.kline.save"),
            Self::ResponseKlineSave => write!(f, "response.kline.save"),
            Self::QueryKlineList => write!(f, "query.kline.list"),
            Self::ResponseKlineList => write!(f, "response.kline.list"),
            Self::CommandTickerSave => write!(f, "command.ticker.save"),
            Self::ResponseTickerSave => write!(f, "response.ticker.save"),
            Self::QueryTickerList => write!(f, "query.ticker.list"),
            Self::ResponseTickerList => write!(f, "response.ticker.list"),
            Self::CommandMarketSubscriptionOrderbookSubscribe => {
                write!(f, "command.market.subscription.orderbook.subscribe")
            }
            Self::ResponseMarketSubscriptionOrderbookSubscribe => {
                write!(f, "response.market.subscription.orderbook.subscribe")
            }
            Self::CommandMarketSubscriptionOrderbookUnsubscribe => {
                write!(f, "command.market.subscription.orderbook.unsubscribe")
            }
            Self::ResponseMarketSubscriptionOrderbookUnsubscribe => {
                write!(f, "response.market.subscription.orderbook.unsubscribe")
            }
            Self::QueryMarketSubscriptionOrderbookList => {
                write!(f, "query.market.subscription.orderbook.list")
            }
            Self::ResponseMarketSubscriptionOrderbookList => {
                write!(f, "response.market.subscription.orderbook.list")
            }
            Self::CommandSubscriptionCreate => write!(f, "command.subscription.create"),
            Self::ResponseSubscriptionCreate => write!(f, "response.subscription.create"),
            Self::QuerySubscriptionList => write!(f, "query.subscription.list"),
            Self::ResponseSubscriptionList => write!(f, "response.subscription.list"),
            Self::EventSubscriptionUpdated => write!(f, "event.subscription.updated"),
            Self::CommandSubscriptionMcCreate => write!(f, "command.subscription.mc.create"),
            Self::ResponseSubscriptionMcCreate => write!(f, "response.subscription.mc.create"),
        }
    }
}

impl Default for RpcMethod {
    fn default() -> RpcMethod {
        Self::QuerySystemInfo
    }
}
