/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcListTradingAccountSubscriptionsParams : Request to list trading account subscriptions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcListTradingAccountSubscriptionsParams {
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
    #[serde(rename = "subscriptionType", skip_serializing_if = "Option::is_none")]
    pub subscription_type: Option<models::SubscriptionType>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::SubscriptionStatus>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::RpcPagination>>,
}

impl RpcListTradingAccountSubscriptionsParams {
    /// Request to list trading account subscriptions
    pub fn new(trading_account_id: uuid::Uuid) -> RpcListTradingAccountSubscriptionsParams {
        RpcListTradingAccountSubscriptionsParams {
            trading_account_id,
            subscription_type: None,
            status: None,
            pagination: None,
        }
    }
}
