/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcGetTradeOrderByIdParams : Request to get a trade order by ID
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcGetTradeOrderByIdParams {
    #[serde(rename = "tradeOrderId")]
    pub trade_order_id: uuid::Uuid,
}

impl RpcGetTradeOrderByIdParams {
    /// Request to get a trade order by ID
    pub fn new(trade_order_id: uuid::Uuid) -> RpcGetTradeOrderByIdParams {
        RpcGetTradeOrderByIdParams { trade_order_id }
    }
}
