/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcListKlinesParams : Request to list klines
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcListKlinesParams {
    #[serde(rename = "instrumentIds", skip_serializing_if = "Option::is_none")]
    pub instrument_ids: Option<Vec<String>>,
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<models::Venue>,
    #[serde(rename = "symbols", skip_serializing_if = "Option::is_none")]
    pub symbols: Option<Vec<String>>,
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<String>,
}

impl RpcListKlinesParams {
    /// Request to list klines
    pub fn new() -> RpcListKlinesParams {
        RpcListKlinesParams {
            instrument_ids: None,
            venue: None,
            symbols: None,
            interval: None,
        }
    }
}

