/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcDeleteTradingAccountParams : Request to delete a trading account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcDeleteTradingAccountParams {
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
}

impl RpcDeleteTradingAccountParams {
    /// Request to delete a trading account
    pub fn new(trading_account_id: uuid::Uuid) -> RpcDeleteTradingAccountParams {
        RpcDeleteTradingAccountParams { trading_account_id }
    }
}
