/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcRotateCredentialParams : Request to rotate a credential
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcRotateCredentialParams {
    #[serde(rename = "credentialId")]
    pub credential_id: uuid::Uuid,
    #[serde(rename = "credentialType", deserialize_with = "Option::deserialize")]
    pub credential_type: Option<models::CredentialType>,
    #[serde(rename = "apiKey", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    #[serde(rename = "secretKey", skip_serializing_if = "Option::is_none")]
    pub secret_key: Option<String>,
    #[serde(rename = "secretPassphrase", skip_serializing_if = "Option::is_none")]
    pub secret_passphrase: Option<String>,
}

impl RpcRotateCredentialParams {
    /// Request to rotate a credential
    pub fn new(credential_id: uuid::Uuid, credential_type: Option<models::CredentialType>) -> RpcRotateCredentialParams {
        RpcRotateCredentialParams {
            credential_id,
            credential_type,
            api_key: None,
            secret_key: None,
            secret_passphrase: None,
        }
    }
}

