/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcListInstrumentsParams : Request to list instruments
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcListInstrumentsParams {
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<models::Venue>,
    #[serde(rename = "symbols", skip_serializing_if = "Option::is_none")]
    pub symbols: Option<Vec<String>>,
    #[serde(rename = "securityType", skip_serializing_if = "Option::is_none")]
    pub security_type: Option<String>,
    #[serde(rename = "instrumentStatus", skip_serializing_if = "Option::is_none")]
    pub instrument_status: Option<String>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
}

impl RpcListInstrumentsParams {
    /// Request to list instruments
    pub fn new() -> RpcListInstrumentsParams {
        RpcListInstrumentsParams {
            venue: None,
            symbols: None,
            security_type: None,
            instrument_status: None,
            limit: None,
            offset: None,
        }
    }
}
