/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcCreateCredentialParams : Request to create a credential
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcCreateCredentialParams {
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
    #[serde(rename = "venue")]
    pub venue: models::Venue,
    #[serde(rename = "credentialType", deserialize_with = "Option::deserialize")]
    pub credential_type: Option<models::CredentialType>,
    #[serde(rename = "apiKey", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    #[serde(rename = "secretKey", skip_serializing_if = "Option::is_none")]
    pub secret_key: Option<String>,
    #[serde(rename = "secretPassphrase", skip_serializing_if = "Option::is_none")]
    pub secret_passphrase: Option<String>,
    #[serde(rename = "nickname", skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
}

impl RpcCreateCredentialParams {
    /// Request to create a credential
    pub fn new(
        trading_account_id: uuid::Uuid,
        venue: models::Venue,
        credential_type: Option<models::CredentialType>,
    ) -> RpcCreateCredentialParams {
        RpcCreateCredentialParams {
            trading_account_id,
            venue,
            credential_type,
            api_key: None,
            secret_key: None,
            secret_passphrase: None,
            nickname: None,
        }
    }
}
