/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcSubmitTradeOrderParams : Request to submit a new trade order
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcSubmitTradeOrderParams {
    #[serde(rename = "tradeOrder")]
    pub trade_order: Box<models::RpcTradeOrder>,
    /// Trading account ID to place order on
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
    /// Idempotency key to prevent duplicate orders
    #[serde(rename = "idempotencyKey", skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
    /// Wait for order to reach terminal state before responding
    #[serde(rename = "awaitClosed", skip_serializing_if = "Option::is_none")]
    pub await_closed: Option<bool>,
}

impl RpcSubmitTradeOrderParams {
    /// Request to submit a new trade order
    pub fn new(
        trade_order: models::RpcTradeOrder,
        trading_account_id: uuid::Uuid,
    ) -> RpcSubmitTradeOrderParams {
        RpcSubmitTradeOrderParams {
            trade_order: Box::new(trade_order),
            trading_account_id,
            idempotency_key: None,
            await_closed: None,
        }
    }
}
