/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcUnsubscribeOrderBookParams : Request to unsubscribe from order book updates
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcUnsubscribeOrderBookParams {
    /// Subscription ID to cancel
    #[serde(rename = "subscriptionId", skip_serializing_if = "Option::is_none")]
    pub subscription_id: Option<uuid::Uuid>,
    /// Instrument ID to unsubscribe
    #[serde(rename = "instrumentId", skip_serializing_if = "Option::is_none")]
    pub instrument_id: Option<String>,
}

impl RpcUnsubscribeOrderBookParams {
    /// Request to unsubscribe from order book updates
    pub fn new() -> RpcUnsubscribeOrderBookParams {
        RpcUnsubscribeOrderBookParams {
            subscription_id: None,
            instrument_id: None,
        }
    }
}
