/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcUpdateTradingAccountParams : Request to update a trading account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcUpdateTradingAccountParams {
    #[serde(rename = "tradingAccount")]
    pub trading_account: Box<models::RpcTradingAccount>,
}

impl RpcUpdateTradingAccountParams {
    /// Request to update a trading account
    pub fn new(trading_account: models::RpcTradingAccount) -> RpcUpdateTradingAccountParams {
        RpcUpdateTradingAccountParams {
            trading_account: Box::new(trading_account),
        }
    }
}

