/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcSystemInfo : System information (same as REST /api/v3 root endpoint)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcSystemInfo {
    /// API name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// API version
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// API description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// API documentation URL
    #[serde(rename = "documentation", skip_serializing_if = "Option::is_none")]
    pub documentation: Option<String>,
}

impl RpcSystemInfo {
    /// System information (same as REST /api/v3 root endpoint)
    pub fn new() -> RpcSystemInfo {
        RpcSystemInfo {
            name: None,
            version: None,
            description: None,
            documentation: None,
        }
    }
}
