/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcListTickersParams : Request to list tickers
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcListTickersParams {
    #[serde(rename = "instrumentIds", skip_serializing_if = "Option::is_none")]
    pub instrument_ids: Option<Vec<String>>,
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<models::Venue>,
    #[serde(rename = "symbols", skip_serializing_if = "Option::is_none")]
    pub symbols: Option<Vec<String>>,
}

impl RpcListTickersParams {
    /// Request to list tickers
    pub fn new() -> RpcListTickersParams {
        RpcListTickersParams {
            instrument_ids: None,
            venue: None,
            symbols: None,
        }
    }
}
