/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcSaveSecuritiesParams : Request to save securities
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcSaveSecuritiesParams {
    #[serde(rename = "securities")]
    pub securities: Vec<models::RpcSecurity>,
}

impl RpcSaveSecuritiesParams {
    /// Request to save securities
    pub fn new(securities: Vec<models::RpcSecurity>) -> RpcSaveSecuritiesParams {
        RpcSaveSecuritiesParams {
            securities,
        }
    }
}

