/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcListSubscriptionsParams : Request to list subscriptions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcListSubscriptionsParams {
    #[serde(rename = "instrumentId", skip_serializing_if = "Option::is_none")]
    pub instrument_id: Option<Vec<String>>,
    #[serde(rename = "subscriptionType", skip_serializing_if = "Option::is_none")]
    pub subscription_type: Option<models::SubscriptionType>,
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<models::Venue>,
}

impl RpcListSubscriptionsParams {
    /// Request to list subscriptions
    pub fn new() -> RpcListSubscriptionsParams {
        RpcListSubscriptionsParams {
            instrument_id: None,
            subscription_type: None,
            venue: None,
        }
    }
}

