/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcTradeOrder : Trade order model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcTradeOrder {
    /// Unique trade order ID
    #[serde(rename = "tradeOrderId", skip_serializing_if = "Option::is_none")]
    pub trade_order_id: Option<uuid::Uuid>,
    /// Client-assigned order ID
    #[serde(rename = "clientOrderId", skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<String>,
    /// Original client order ID (for cancel/replace)
    #[serde(rename = "originalClientOrderId", skip_serializing_if = "Option::is_none")]
    pub original_client_order_id: Option<String>,
    /// Order ID from external venue
    #[serde(rename = "externalOrderId", skip_serializing_if = "Option::is_none")]
    pub external_order_id: Option<String>,
    /// Idempotency key
    #[serde(rename = "idempotencyKey", skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
    /// Trading venue
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<String>,
    /// Trading account ID
    #[serde(rename = "tradingAccountId", skip_serializing_if = "Option::is_none")]
    pub trading_account_id: Option<uuid::Uuid>,
    /// External account ID at venue
    #[serde(rename = "externalTradingAccountId", skip_serializing_if = "Option::is_none")]
    pub external_trading_account_id: Option<String>,
    /// Instrument ID (VENUE:BASE/QUOTE)
    #[serde(rename = "instrumentId", skip_serializing_if = "Option::is_none")]
    pub instrument_id: Option<String>,
    /// Symbol at external venue
    #[serde(rename = "externalSymbol", skip_serializing_if = "Option::is_none")]
    pub external_symbol: Option<String>,
    /// Base asset
    #[serde(rename = "baseAsset", skip_serializing_if = "Option::is_none")]
    pub base_asset: Option<String>,
    /// Quote asset
    #[serde(rename = "quoteAsset", skip_serializing_if = "Option::is_none")]
    pub quote_asset: Option<String>,
    #[serde(rename = "orderType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub order_type: Option<Option<models::OrderType>>,
    #[serde(rename = "orderSide", skip_serializing_if = "Option::is_none")]
    pub order_side: Option<models::OrderSide>,
    #[serde(rename = "quantityType", skip_serializing_if = "Option::is_none")]
    pub quantity_type: Option<models::QuantityType>,
    /// Order quantity (decimal string)
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<String>,
    /// Quantity in quote currency
    #[serde(rename = "quoteCurrencyQuantity", skip_serializing_if = "Option::is_none")]
    pub quote_currency_quantity: Option<String>,
    /// Quantity as position percentage
    #[serde(rename = "positionPercentage", skip_serializing_if = "Option::is_none")]
    pub position_percentage: Option<String>,
    #[serde(rename = "quantityRounding", skip_serializing_if = "Option::is_none")]
    pub quantity_rounding: Option<models::QuantityRounding>,
    /// Limit price (decimal string)
    #[serde(rename = "limitPrice", skip_serializing_if = "Option::is_none")]
    pub limit_price: Option<String>,
    /// Stop price (decimal string)
    #[serde(rename = "stopPrice", skip_serializing_if = "Option::is_none")]
    pub stop_price: Option<String>,
    #[serde(rename = "timeInForce", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub time_in_force: Option<Option<models::TimeInForce>>,
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<models::OrderStatus>>,
    /// Average executed price
    #[serde(rename = "executedPrice", skip_serializing_if = "Option::is_none")]
    pub executed_price: Option<String>,
    /// Percentage of order filled
    #[serde(rename = "executedPercentage", skip_serializing_if = "Option::is_none")]
    pub executed_percentage: Option<String>,
    /// Quantity executed
    #[serde(rename = "executedQuantity", skip_serializing_if = "Option::is_none")]
    pub executed_quantity: Option<String>,
    /// Total cost in quote currency
    #[serde(rename = "executedCost", skip_serializing_if = "Option::is_none")]
    pub executed_cost: Option<String>,
    /// Fees charged
    #[serde(rename = "fees", skip_serializing_if = "Option::is_none")]
    pub fees: Option<Vec<models::RpcSecurityQuantity>>,
    /// Reason for cancellation
    #[serde(rename = "cancelReason", skip_serializing_if = "Option::is_none")]
    pub cancel_reason: Option<String>,
    /// Reason for rejection
    #[serde(rename = "rejectReason", skip_serializing_if = "Option::is_none")]
    pub reject_reason: Option<String>,
    /// Order creation time
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Last update time
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// Order expiration time (for GTD)
    #[serde(rename = "expireAt", skip_serializing_if = "Option::is_none")]
    pub expire_at: Option<String>,
    /// Time of last execution
    #[serde(rename = "lastExecutionAt", skip_serializing_if = "Option::is_none")]
    pub last_execution_at: Option<String>,
    /// Time of cancellation
    #[serde(rename = "canceledAt", skip_serializing_if = "Option::is_none")]
    pub canceled_at: Option<String>,
}

impl RpcTradeOrder {
    /// Trade order model
    pub fn new() -> RpcTradeOrder {
        RpcTradeOrder {
            trade_order_id: None,
            client_order_id: None,
            original_client_order_id: None,
            external_order_id: None,
            idempotency_key: None,
            venue: None,
            trading_account_id: None,
            external_trading_account_id: None,
            instrument_id: None,
            external_symbol: None,
            base_asset: None,
            quote_asset: None,
            order_type: None,
            order_side: None,
            quantity_type: None,
            quantity: None,
            quote_currency_quantity: None,
            position_percentage: None,
            quantity_rounding: None,
            limit_price: None,
            stop_price: None,
            time_in_force: None,
            status: None,
            executed_price: None,
            executed_percentage: None,
            executed_quantity: None,
            executed_cost: None,
            fees: None,
            cancel_reason: None,
            reject_reason: None,
            created_at: None,
            updated_at: None,
            expire_at: None,
            last_execution_at: None,
            canceled_at: None,
        }
    }
}

