/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcSaveOrderBooksParams : Request to save order books
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcSaveOrderBooksParams {
    #[serde(rename = "orderBooks")]
    pub order_books: Vec<models::RpcOrderBook>,
}

impl RpcSaveOrderBooksParams {
    /// Request to save order books
    pub fn new(order_books: Vec<models::RpcOrderBook>) -> RpcSaveOrderBooksParams {
        RpcSaveOrderBooksParams { order_books }
    }
}
