/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcSubscribeTradingAccountStreamParams : Request to subscribe to trading account stream
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcSubscribeTradingAccountStreamParams {
    #[serde(rename = "tradingAccount")]
    pub trading_account: Box<models::RpcTradingAccount>,
    #[serde(rename = "subscriptionType")]
    pub subscription_type: models::SubscriptionType,
}

impl RpcSubscribeTradingAccountStreamParams {
    /// Request to subscribe to trading account stream
    pub fn new(trading_account: models::RpcTradingAccount, subscription_type: models::SubscriptionType) -> RpcSubscribeTradingAccountStreamParams {
        RpcSubscribeTradingAccountStreamParams {
            trading_account: Box::new(trading_account),
            subscription_type,
        }
    }
}

