/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcSaveCredentialParams : Request to save a credential
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcSaveCredentialParams {
    #[serde(rename = "credential")]
    pub credential: Box<models::RpcTradingAccountCredential>,
}

impl RpcSaveCredentialParams {
    /// Request to save a credential
    pub fn new(credential: models::RpcTradingAccountCredential) -> RpcSaveCredentialParams {
        RpcSaveCredentialParams {
            credential: Box::new(credential),
        }
    }
}
