/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcDisconnectTradingAccountParams : Request to disconnect a trading account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcDisconnectTradingAccountParams {
    /// Trading account ID to disconnect
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
}

impl RpcDisconnectTradingAccountParams {
    /// Request to disconnect a trading account
    pub fn new(trading_account_id: uuid::Uuid) -> RpcDisconnectTradingAccountParams {
        RpcDisconnectTradingAccountParams {
            trading_account_id,
        }
    }
}

