/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcTradingAccount : Trading account model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcTradingAccount {
    /// Unique trading account ID
    #[serde(rename = "tradingAccountId", skip_serializing_if = "Option::is_none")]
    pub trading_account_id: Option<uuid::Uuid>,
    /// User ID
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<uuid::Uuid>,
    /// Tenant identifier for multi-tenancy
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
    /// Account nickname
    #[serde(rename = "nickname", skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
    /// External account ID at venue
    #[serde(rename = "externalAccountId", skip_serializing_if = "Option::is_none")]
    pub external_account_id: Option<String>,
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<models::Venue>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::TradingAccountStatus>,
    #[serde(rename = "accountType", skip_serializing_if = "Option::is_none")]
    pub account_type: Option<models::TradingAccountType>,
    /// Type of account on the exchange (set by market connector)
    #[serde(
        rename = "externalAccountType",
        skip_serializing_if = "Option::is_none"
    )]
    pub external_account_type: Option<String>,
    #[serde(
        rename = "positionMode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub position_mode: Option<Option<models::PositionMode>>,
    #[serde(
        rename = "collateralMode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub collateral_mode: Option<Option<models::CollateralMode>>,
    #[serde(
        rename = "marginMode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub margin_mode: Option<Option<models::MarginMode>>,
    /// Account credentials
    #[serde(rename = "credentials", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<Vec<models::RpcTradingAccountCredential>>,
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<Box<models::RpcTradingAccountConfig>>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl RpcTradingAccount {
    /// Trading account model
    pub fn new() -> RpcTradingAccount {
        RpcTradingAccount {
            trading_account_id: None,
            user_id: None,
            tenant_id: None,
            nickname: None,
            external_account_id: None,
            venue: None,
            status: None,
            account_type: None,
            external_account_type: None,
            position_mode: None,
            collateral_mode: None,
            margin_mode: None,
            credentials: None,
            config: None,
            created_at: None,
            updated_at: None,
        }
    }
}
