/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcListCredentialsParams : Request to list credentials
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcListCredentialsParams {
    #[serde(rename = "credentialIds", skip_serializing_if = "Option::is_none")]
    pub credential_ids: Option<Vec<uuid::Uuid>>,
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<models::Venue>,
    #[serde(
        rename = "credentialType",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub credential_type: Option<Option<models::CredentialType>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::CredentialStatus>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::RpcPagination>>,
}

impl RpcListCredentialsParams {
    /// Request to list credentials
    pub fn new() -> RpcListCredentialsParams {
        RpcListCredentialsParams {
            credential_ids: None,
            venue: None,
            credential_type: None,
            status: None,
            pagination: None,
        }
    }
}
