/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcListTradingAccountsParams : Request to list trading accounts
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcListTradingAccountsParams {
    /// Filter by specific account ID
    #[serde(rename = "tradingAccountId", skip_serializing_if = "Option::is_none")]
    pub trading_account_id: Option<uuid::Uuid>,
    /// Filter by venue
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::TradingAccountStatus>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::RpcPagination>>,
}

impl RpcListTradingAccountsParams {
    /// Request to list trading accounts
    pub fn new() -> RpcListTradingAccountsParams {
        RpcListTradingAccountsParams {
            trading_account_id: None,
            venue: None,
            status: None,
            pagination: None,
        }
    }
}
