/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcListPortfoliosParams : Request to list portfolios
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcListPortfoliosParams {
    /// Filter by trading account ID
    #[serde(rename = "tradingAccountId", skip_serializing_if = "Option::is_none")]
    pub trading_account_id: Option<uuid::Uuid>,
    /// Filter by venue
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<String>,
    /// Filter by currency
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::RpcPagination>>,
}

impl RpcListPortfoliosParams {
    /// Request to list portfolios
    pub fn new() -> RpcListPortfoliosParams {
        RpcListPortfoliosParams {
            trading_account_id: None,
            venue: None,
            currency: None,
            pagination: None,
        }
    }
}
