/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcUnsubscribeTradingAccountStreamParams : Request to unsubscribe from trading account stream
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcUnsubscribeTradingAccountStreamParams {
    #[serde(rename = "subscriptionId", skip_serializing_if = "Option::is_none")]
    pub subscription_id: Option<uuid::Uuid>,
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
}

impl RpcUnsubscribeTradingAccountStreamParams {
    /// Request to unsubscribe from trading account stream
    pub fn new(trading_account_id: uuid::Uuid) -> RpcUnsubscribeTradingAccountStreamParams {
        RpcUnsubscribeTradingAccountStreamParams {
            subscription_id: None,
            trading_account_id,
        }
    }
}

