/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcSavePortfolioParams : Request to save a portfolio
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcSavePortfolioParams {
    #[serde(rename = "portfolio")]
    pub portfolio: Box<models::RpcPortfolio>,
}

impl RpcSavePortfolioParams {
    /// Request to save a portfolio
    pub fn new(portfolio: models::RpcPortfolio) -> RpcSavePortfolioParams {
        RpcSavePortfolioParams {
            portfolio: Box::new(portfolio),
        }
    }
}

