/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcSaveTradingAccountsParams : Request to save multiple trading accounts
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcSaveTradingAccountsParams {
    #[serde(rename = "tradingAccounts")]
    pub trading_accounts: Vec<models::RpcTradingAccount>,
}

impl RpcSaveTradingAccountsParams {
    /// Request to save multiple trading accounts
    pub fn new(trading_accounts: Vec<models::RpcTradingAccount>) -> RpcSaveTradingAccountsParams {
        RpcSaveTradingAccountsParams { trading_accounts }
    }
}
