/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcSecurity : Security (base asset)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcSecurity {
    #[serde(rename = "securityId", skip_serializing_if = "Option::is_none")]
    pub security_id: Option<String>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "externalSymbol", skip_serializing_if = "Option::is_none")]
    pub external_symbol: Option<String>,
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<models::Venue>,
}

impl RpcSecurity {
    /// Security (base asset)
    pub fn new() -> RpcSecurity {
        RpcSecurity {
            security_id: None,
            symbol: None,
            external_symbol: None,
            venue: None,
        }
    }
}
