/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcRevokeCredentialParams : Request to revoke a credential
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcRevokeCredentialParams {
    #[serde(rename = "credentialId")]
    pub credential_id: uuid::Uuid,
}

impl RpcRevokeCredentialParams {
    /// Request to revoke a credential
    pub fn new(credential_id: uuid::Uuid) -> RpcRevokeCredentialParams {
        RpcRevokeCredentialParams {
            credential_id,
        }
    }
}

