/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcVerifyCredentialParams : Request to verify credentials
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcVerifyCredentialParams {
    #[serde(rename = "credentialIds", skip_serializing_if = "Option::is_none")]
    pub credential_ids: Option<Vec<uuid::Uuid>>,
    #[serde(rename = "credentials", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<Vec<models::RpcTradingAccountCredential>>,
}

impl RpcVerifyCredentialParams {
    /// Request to verify credentials
    pub fn new() -> RpcVerifyCredentialParams {
        RpcVerifyCredentialParams {
            credential_ids: None,
            credentials: None,
        }
    }
}

