/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcEnableInstrumentParams : Request to enable an instrument
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcEnableInstrumentParams {
    #[serde(rename = "instrumentId")]
    pub instrument_id: String,
}

impl RpcEnableInstrumentParams {
    /// Request to enable an instrument
    pub fn new(instrument_id: String) -> RpcEnableInstrumentParams {
        RpcEnableInstrumentParams {
            instrument_id,
        }
    }
}

