/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcOhlcv : OHLCV candlestick data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcOhlcv {
    /// Open time
    #[serde(rename = "t", skip_serializing_if = "Option::is_none")]
    pub t: Option<String>,
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<String>,
    /// Open price (decimal)
    #[serde(rename = "o", skip_serializing_if = "Option::is_none")]
    pub o: Option<String>,
    /// High price (decimal)
    #[serde(rename = "h", skip_serializing_if = "Option::is_none")]
    pub h: Option<String>,
    /// Low price (decimal)
    #[serde(rename = "l", skip_serializing_if = "Option::is_none")]
    pub l: Option<String>,
    /// Close price (decimal)
    #[serde(rename = "c", skip_serializing_if = "Option::is_none")]
    pub c: Option<String>,
    /// Volume (decimal)
    #[serde(rename = "v", skip_serializing_if = "Option::is_none")]
    pub v: Option<String>,
}

impl RpcOhlcv {
    /// OHLCV candlestick data
    pub fn new() -> RpcOhlcv {
        RpcOhlcv {
            t: None,
            interval: None,
            o: None,
            h: None,
            l: None,
            c: None,
            v: None,
        }
    }
}

