/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcBalanceEntry : Balance entry for an asset
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcBalanceEntry {
    #[serde(rename = "balanceId", skip_serializing_if = "Option::is_none")]
    pub balance_id: Option<uuid::Uuid>,
    #[serde(rename = "externalBalanceId", skip_serializing_if = "Option::is_none")]
    pub external_balance_id: Option<String>,
    #[serde(rename = "tradingAccountId", skip_serializing_if = "Option::is_none")]
    pub trading_account_id: Option<uuid::Uuid>,
    /// Asset symbol
    #[serde(rename = "securitySymbol", skip_serializing_if = "Option::is_none")]
    pub security_symbol: Option<String>,
    #[serde(rename = "securityType", skip_serializing_if = "Option::is_none")]
    pub security_type: Option<models::SecurityType>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::BalanceStatus>,
    /// Available balance
    #[serde(rename = "free", skip_serializing_if = "Option::is_none")]
    pub free: Option<String>,
    /// Locked balance
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<String>,
    /// Frozen balance
    #[serde(rename = "frozen", skip_serializing_if = "Option::is_none")]
    pub frozen: Option<String>,
    /// Borrowed amount
    #[serde(rename = "borrowed", skip_serializing_if = "Option::is_none")]
    pub borrowed: Option<String>,
    /// Interest owed
    #[serde(rename = "interestOwed", skip_serializing_if = "Option::is_none")]
    pub interest_owed: Option<String>,
    /// Total balance
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<String>,
    /// Net equity
    #[serde(rename = "net", skip_serializing_if = "Option::is_none")]
    pub net: Option<String>,
    #[serde(rename = "collateralWeight", skip_serializing_if = "Option::is_none")]
    pub collateral_weight: Option<String>,
    #[serde(rename = "collateralValue", skip_serializing_if = "Option::is_none")]
    pub collateral_value: Option<String>,
    #[serde(rename = "collateralEnabled", skip_serializing_if = "Option::is_none")]
    pub collateral_enabled: Option<bool>,
    #[serde(rename = "crossMargin", skip_serializing_if = "Option::is_none")]
    pub cross_margin: Option<String>,
    #[serde(rename = "isolatedMargin", skip_serializing_if = "Option::is_none")]
    pub isolated_margin: Option<String>,
    #[serde(rename = "marginRatio", skip_serializing_if = "Option::is_none")]
    pub margin_ratio: Option<String>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl RpcBalanceEntry {
    /// Balance entry for an asset
    pub fn new() -> RpcBalanceEntry {
        RpcBalanceEntry {
            balance_id: None,
            external_balance_id: None,
            trading_account_id: None,
            security_symbol: None,
            security_type: None,
            status: None,
            free: None,
            locked: None,
            frozen: None,
            borrowed: None,
            interest_owed: None,
            total: None,
            net: None,
            collateral_weight: None,
            collateral_value: None,
            collateral_enabled: None,
            cross_margin: None,
            isolated_margin: None,
            margin_ratio: None,
            created_at: None,
            updated_at: None,
        }
    }
}
