/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcDeleteSecuritiesParams : Request to delete securities
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcDeleteSecuritiesParams {
    #[serde(rename = "securityIds")]
    pub security_ids: Vec<uuid::Uuid>,
}

impl RpcDeleteSecuritiesParams {
    /// Request to delete securities
    pub fn new(security_ids: Vec<uuid::Uuid>) -> RpcDeleteSecuritiesParams {
        RpcDeleteSecuritiesParams { security_ids }
    }
}
