/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcHealthCheck : Health check data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcHealthCheck {
    #[serde(rename = "status")]
    pub status: models::HealthStatus,
    /// Timestamp in ISO 8601 format (RFC3339). This is the native format used by Go's time.Time.
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    /// API version
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "checks", skip_serializing_if = "Option::is_none")]
    pub checks: Option<Box<models::Health200ResponseChecks>>,
}

impl RpcHealthCheck {
    /// Health check data
    pub fn new(status: models::HealthStatus, timestamp: String, version: String) -> RpcHealthCheck {
        RpcHealthCheck {
            status,
            timestamp,
            version,
            checks: None,
        }
    }
}

