/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcPortfolioSummary : Portfolio summary with aggregated metrics
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcPortfolioSummary {
    #[serde(rename = "portfolioSummaryId", skip_serializing_if = "Option::is_none")]
    pub portfolio_summary_id: Option<uuid::Uuid>,
    #[serde(rename = "tradingAccountId", skip_serializing_if = "Option::is_none")]
    pub trading_account_id: Option<uuid::Uuid>,
    /// Summary currency
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(rename = "leverage", skip_serializing_if = "Option::is_none")]
    pub leverage: Option<i32>,
    /// Total equity
    #[serde(rename = "equity", skip_serializing_if = "Option::is_none")]
    pub equity: Option<String>,
    /// Margin collateral
    #[serde(rename = "margin", skip_serializing_if = "Option::is_none")]
    pub margin: Option<String>,
    /// Borrowed margin
    #[serde(rename = "marginLoan", skip_serializing_if = "Option::is_none")]
    pub margin_loan: Option<String>,
    /// Margin usage rate
    #[serde(rename = "marginUsage", skip_serializing_if = "Option::is_none")]
    pub margin_usage: Option<String>,
    /// Required margin
    #[serde(rename = "marginRequirement", skip_serializing_if = "Option::is_none")]
    pub margin_requirement: Option<String>,
    /// Margin level
    #[serde(rename = "marginLevel", skip_serializing_if = "Option::is_none")]
    pub margin_level: Option<String>,
    /// Available credit
    #[serde(rename = "credit", skip_serializing_if = "Option::is_none")]
    pub credit: Option<String>,
    /// Total risk exposure
    #[serde(rename = "riskExposure", skip_serializing_if = "Option::is_none")]
    pub risk_exposure: Option<String>,
    /// Maximum risk exposure
    #[serde(rename = "maxRiskExposure", skip_serializing_if = "Option::is_none")]
    pub max_risk_exposure: Option<String>,
    /// Risk exposure rate
    #[serde(rename = "riskExposureRate", skip_serializing_if = "Option::is_none")]
    pub risk_exposure_rate: Option<String>,
}

impl RpcPortfolioSummary {
    /// Portfolio summary with aggregated metrics
    pub fn new() -> RpcPortfolioSummary {
        RpcPortfolioSummary {
            portfolio_summary_id: None,
            trading_account_id: None,
            currency: None,
            leverage: None,
            equity: None,
            margin: None,
            margin_loan: None,
            margin_usage: None,
            margin_requirement: None,
            margin_level: None,
            credit: None,
            risk_exposure: None,
            max_risk_exposure: None,
            risk_exposure_rate: None,
        }
    }
}

