/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcListSecuritiesParams : Request to list securities
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcListSecuritiesParams {
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<models::Venue>,
    #[serde(rename = "securities", skip_serializing_if = "Option::is_none")]
    pub securities: Option<Vec<String>>,
    #[serde(rename = "externalSymbols", skip_serializing_if = "Option::is_none")]
    pub external_symbols: Option<Vec<String>>,
}

impl RpcListSecuritiesParams {
    /// Request to list securities
    pub fn new() -> RpcListSecuritiesParams {
        RpcListSecuritiesParams {
            venue: None,
            securities: None,
            external_symbols: None,
        }
    }
}

