/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcOrderBook : Order book model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcOrderBook {
    /// Instrument ID
    #[serde(rename = "instrumentId", skip_serializing_if = "Option::is_none")]
    pub instrument_id: Option<String>,
    /// Venue
    #[serde(rename = "venue", skip_serializing_if = "Option::is_none")]
    pub venue: Option<String>,
    /// Trading pair symbol
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Bid orders (sorted by price descending)
    #[serde(rename = "bids", skip_serializing_if = "Option::is_none")]
    pub bids: Option<Vec<models::RpcOrderBookLevel>>,
    /// Ask orders (sorted by price ascending)
    #[serde(rename = "asks", skip_serializing_if = "Option::is_none")]
    pub asks: Option<Vec<models::RpcOrderBookLevel>>,
    /// Timestamp in ISO 8601 format (RFC3339). This is the native format used by Go's time.Time.
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    /// Sequence number for ordering updates
    #[serde(rename = "sequenceNumber", skip_serializing_if = "Option::is_none")]
    pub sequence_number: Option<i64>,
}

impl RpcOrderBook {
    /// Order book model
    pub fn new() -> RpcOrderBook {
        RpcOrderBook {
            instrument_id: None,
            venue: None,
            symbol: None,
            bids: None,
            asks: None,
            timestamp: None,
            sequence_number: None,
        }
    }
}

