/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcCreateSubscriptionParams : Request to create a market data subscription
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcCreateSubscriptionParams {
    #[serde(rename = "venue")]
    pub venue: models::Venue,
    #[serde(rename = "instruments", skip_serializing_if = "Option::is_none")]
    pub instruments: Option<Vec<String>>,
    #[serde(rename = "subscriptionType")]
    pub subscription_type: models::SubscriptionType,
}

impl RpcCreateSubscriptionParams {
    /// Request to create a market data subscription
    pub fn new(venue: models::Venue, subscription_type: models::SubscriptionType) -> RpcCreateSubscriptionParams {
        RpcCreateSubscriptionParams {
            venue,
            instruments: None,
            subscription_type,
        }
    }
}

