/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcListTradingAccountOperationsParams : Request to list trading account operations
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcListTradingAccountOperationsParams {
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::RpcPagination>>,
}

impl RpcListTradingAccountOperationsParams {
    /// Request to list trading account operations
    pub fn new(trading_account_id: uuid::Uuid) -> RpcListTradingAccountOperationsParams {
        RpcListTradingAccountOperationsParams {
            trading_account_id,
            pagination: None,
        }
    }
}

