/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcGetTradeOrderParams : Request to get a specific trade order
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcGetTradeOrderParams {
    /// Trade order ID
    #[serde(rename = "tradeOrderId", skip_serializing_if = "Option::is_none")]
    pub trade_order_id: Option<uuid::Uuid>,
    /// Trading account ID
    #[serde(rename = "tradingAccountId", skip_serializing_if = "Option::is_none")]
    pub trading_account_id: Option<uuid::Uuid>,
    /// Client order ID
    #[serde(rename = "clientOrderId", skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<String>,
    /// External order ID
    #[serde(rename = "externalOrderId", skip_serializing_if = "Option::is_none")]
    pub external_order_id: Option<String>,
}

impl RpcGetTradeOrderParams {
    /// Request to get a specific trade order
    pub fn new() -> RpcGetTradeOrderParams {
        RpcGetTradeOrderParams {
            trade_order_id: None,
            trading_account_id: None,
            client_order_id: None,
            external_order_id: None,
        }
    }
}

