/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcPagination : Pagination parameters and metadata
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcPagination {
    /// Offset for pagination
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    /// Limit for pagination
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    /// Total number of items
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    /// Cursor for next page
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Whether there are more items
    #[serde(rename = "hasNext", skip_serializing_if = "Option::is_none")]
    pub has_next: Option<bool>,
}

impl RpcPagination {
    /// Pagination parameters and metadata
    pub fn new() -> RpcPagination {
        RpcPagination {
            offset: None,
            limit: None,
            total: None,
            cursor: None,
            has_next: None,
        }
    }
}
