/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcPositionEntry : Position entry for an instrument
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcPositionEntry {
    #[serde(rename = "positionId", skip_serializing_if = "Option::is_none")]
    pub position_id: Option<uuid::Uuid>,
    #[serde(rename = "externalPositionId", skip_serializing_if = "Option::is_none")]
    pub external_position_id: Option<String>,
    #[serde(rename = "tradingAccountId", skip_serializing_if = "Option::is_none")]
    pub trading_account_id: Option<uuid::Uuid>,
    #[serde(rename = "securitySymbol", skip_serializing_if = "Option::is_none")]
    pub security_symbol: Option<String>,
    /// Instrument ID
    #[serde(rename = "instrumentId", skip_serializing_if = "Option::is_none")]
    pub instrument_id: Option<String>,
    #[serde(rename = "securityType", skip_serializing_if = "Option::is_none")]
    pub security_type: Option<models::SecurityType>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::PositionStatus>,
    #[serde(rename = "positionSide", skip_serializing_if = "Option::is_none")]
    pub position_side: Option<models::PositionSide>,
    /// Position quantity
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<String>,
    #[serde(rename = "entryPrice", skip_serializing_if = "Option::is_none")]
    pub entry_price: Option<String>,
    #[serde(rename = "exitPrice", skip_serializing_if = "Option::is_none")]
    pub exit_price: Option<String>,
    #[serde(rename = "currentPrice", skip_serializing_if = "Option::is_none")]
    pub current_price: Option<String>,
    #[serde(rename = "unrealizedPnl", skip_serializing_if = "Option::is_none")]
    pub unrealized_pnl: Option<String>,
    #[serde(rename = "realizedPnl", skip_serializing_if = "Option::is_none")]
    pub realized_pnl: Option<String>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl RpcPositionEntry {
    /// Position entry for an instrument
    pub fn new() -> RpcPositionEntry {
        RpcPositionEntry {
            position_id: None,
            external_position_id: None,
            trading_account_id: None,
            security_symbol: None,
            instrument_id: None,
            security_type: None,
            status: None,
            position_side: None,
            quantity: None,
            entry_price: None,
            exit_price: None,
            current_price: None,
            unrealized_pnl: None,
            realized_pnl: None,
            created_at: None,
            updated_at: None,
        }
    }
}
