/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RpcGetPortfolioParams : Request to get portfolio for a trading account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcGetPortfolioParams {
    /// Trading account ID
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
}

impl RpcGetPortfolioParams {
    /// Request to get portfolio for a trading account
    pub fn new(trading_account_id: uuid::Uuid) -> RpcGetPortfolioParams {
        RpcGetPortfolioParams {
            trading_account_id,
        }
    }
}

