/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecurityType : Type of financial instrument
/// Type of financial instrument
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecurityType {
    #[serde(rename = "STOCK")]
    Stock,
    #[serde(rename = "CRYPTO")]
    Crypto,
    #[serde(rename = "CURRENCY")]
    Currency,
    #[serde(rename = "COMMODITY")]
    Commodity,
    #[serde(rename = "INDEX")]
    Index,
    #[serde(rename = "BOND")]
    Bond,
    #[serde(rename = "OPTION")]
    Option,
    #[serde(rename = "FUTURES")]
    Futures,
    #[serde(rename = "PERPETUAL")]
    Perpetual,
}

impl std::fmt::Display for SecurityType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Stock => write!(f, "STOCK"),
            Self::Crypto => write!(f, "CRYPTO"),
            Self::Currency => write!(f, "CURRENCY"),
            Self::Commodity => write!(f, "COMMODITY"),
            Self::Index => write!(f, "INDEX"),
            Self::Bond => write!(f, "BOND"),
            Self::Option => write!(f, "OPTION"),
            Self::Futures => write!(f, "FUTURES"),
            Self::Perpetual => write!(f, "PERPETUAL"),
        }
    }
}

impl Default for SecurityType {
    fn default() -> SecurityType {
        Self::Stock
    }
}
