/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecurityQuantity {
    /// Security ID in format venue:symbol (e.g., BINANCE:BTC)
    #[serde(rename = "security")]
    pub security: String,
    /// Asset symbol (e.g., BTC, USDT, BNB)
    #[serde(rename = "asset")]
    pub asset: String,
    #[serde(rename = "venue")]
    pub venue: models::Venue,
    /// Decimal value as string to preserve precision
    #[serde(rename = "quantity")]
    pub quantity: String,
}

impl SecurityQuantity {
    pub fn new(
        security: String,
        asset: String,
        venue: models::Venue,
        quantity: String,
    ) -> SecurityQuantity {
        SecurityQuantity {
            security,
            asset,
            venue,
            quantity,
        }
    }
}
