/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitTradeOrderRequest {
    /// UUID string
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
    /// Instrument ID in format {VENUE}:{BASE}/{QUOTE}
    #[serde(rename = "instrumentId")]
    pub instrument_id: String,
    /// Idempotency key to prevent duplicate request processing
    #[serde(rename = "idempotencyKey", skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
    /// Client-provided order ID, used as idempotency key
    #[serde(rename = "clientOrderId", skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<String>,
    #[serde(rename = "orderSide")]
    pub order_side: models::OrderSide,
    #[serde(rename = "orderType", deserialize_with = "Option::deserialize")]
    pub order_type: Option<models::OrderType>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "limitPrice", skip_serializing_if = "Option::is_none")]
    pub limit_price: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "stopPrice", skip_serializing_if = "Option::is_none")]
    pub stop_price: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "quantity")]
    pub quantity: String,
    #[serde(rename = "quantityType", skip_serializing_if = "Option::is_none")]
    pub quantity_type: Option<models::OrderQuantityType>,
    #[serde(rename = "quantityRounding", skip_serializing_if = "Option::is_none")]
    pub quantity_rounding: Option<models::QuantityRounding>,
    /// UUID string
    #[serde(rename = "positionId", skip_serializing_if = "Option::is_none")]
    pub position_id: Option<uuid::Uuid>,
    #[serde(rename = "timeInForce", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub time_in_force: Option<Option<models::TimeInForce>>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "expireAt", skip_serializing_if = "Option::is_none")]
    pub expire_at: Option<i64>,
    /// UUID string
    #[serde(rename = "quoteId", skip_serializing_if = "Option::is_none")]
    pub quote_id: Option<uuid::Uuid>,
    /// Leverage
    #[serde(rename = "leverage", skip_serializing_if = "Option::is_none")]
    pub leverage: Option<i32>,
    /// If true, the API will wait up to 1 second for the order to reach a closed/finalized state (FILLED, REJECTED, EXPIRED, CANCELLED) before responding. If false or omitted, returns immediately with the initial order state. Useful for market orders that typically fill immediately. 
    #[serde(rename = "awaitClosed", skip_serializing_if = "Option::is_none")]
    pub await_closed: Option<bool>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "takeProfitPrice", skip_serializing_if = "Option::is_none")]
    pub take_profit_price: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "takeProfitLimitPrice", skip_serializing_if = "Option::is_none")]
    pub take_profit_limit_price: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "stopLossPrice", skip_serializing_if = "Option::is_none")]
    pub stop_loss_price: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "stopLossLimitPrice", skip_serializing_if = "Option::is_none")]
    pub stop_loss_limit_price: Option<String>,
    #[serde(rename = "takeProfitTimeInForce", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub take_profit_time_in_force: Option<Option<models::TimeInForce>>,
    #[serde(rename = "stopLossTimeInForce", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub stop_loss_time_in_force: Option<Option<models::TimeInForce>>,
}

impl SubmitTradeOrderRequest {
    pub fn new(trading_account_id: uuid::Uuid, instrument_id: String, order_side: models::OrderSide, order_type: Option<models::OrderType>, quantity: String) -> SubmitTradeOrderRequest {
        SubmitTradeOrderRequest {
            trading_account_id,
            instrument_id,
            idempotency_key: None,
            client_order_id: None,
            order_side,
            order_type,
            limit_price: None,
            stop_price: None,
            quantity,
            quantity_type: None,
            quantity_rounding: None,
            position_id: None,
            time_in_force: None,
            expire_at: None,
            quote_id: None,
            leverage: None,
            await_closed: None,
            take_profit_price: None,
            take_profit_limit_price: None,
            stop_loss_price: None,
            stop_loss_limit_price: None,
            take_profit_time_in_force: None,
            stop_loss_time_in_force: None,
        }
    }
}

