/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubscriptionType : Type of data subscription
/// Type of data subscription
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SubscriptionType {
    #[serde(rename = "ORDERBOOK")]
    Orderbook,
    #[serde(rename = "TRADE")]
    Trade,
    #[serde(rename = "TICKER")]
    Ticker,
    #[serde(rename = "KLINE")]
    Kline,
    #[serde(rename = "USER_DATA")]
    UserData,
    #[serde(rename = "PORTFOLIO")]
    Portfolio,
    #[serde(rename = "EXECUTION_REPORT")]
    ExecutionReport,
    #[serde(rename = "TRADING_ACCOUNT")]
    TradingAccount,
}

impl std::fmt::Display for SubscriptionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Orderbook => write!(f, "ORDERBOOK"),
            Self::Trade => write!(f, "TRADE"),
            Self::Ticker => write!(f, "TICKER"),
            Self::Kline => write!(f, "KLINE"),
            Self::UserData => write!(f, "USER_DATA"),
            Self::Portfolio => write!(f, "PORTFOLIO"),
            Self::ExecutionReport => write!(f, "EXECUTION_REPORT"),
            Self::TradingAccount => write!(f, "TRADING_ACCOUNT"),
        }
    }
}

impl Default for SubscriptionType {
    fn default() -> SubscriptionType {
        Self::Orderbook
    }
}
