/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Subscription {
    /// UUID string
    #[serde(rename = "subscriptionId")]
    pub subscription_id: uuid::Uuid,
    #[serde(rename = "venue")]
    pub venue: models::Venue,
    /// UUID string
    #[serde(rename = "tradingAccountId", skip_serializing_if = "Option::is_none")]
    pub trading_account_id: Option<uuid::Uuid>,
    /// Instrument ID in format {VENUE}:{BASE}/{QUOTE}
    #[serde(rename = "instrumentId", skip_serializing_if = "Option::is_none")]
    pub instrument_id: Option<String>,
    #[serde(rename = "subscriptionType")]
    pub subscription_type: models::SubscriptionType,
    #[serde(rename = "status")]
    pub status: models::SubscriptionStatus,
    /// Unix timestamp in milliseconds
    #[serde(rename = "createdAt")]
    pub created_at: i64,
    /// Creation timestamp in ISO 8601 format
    #[serde(rename = "createdAtDateTime", skip_serializing_if = "Option::is_none")]
    pub created_at_date_time: Option<String>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "updatedAt")]
    pub updated_at: i64,
    /// Last update timestamp in ISO 8601 format
    #[serde(rename = "updatedAtDateTime", skip_serializing_if = "Option::is_none")]
    pub updated_at_date_time: Option<String>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "lastEventTimestamp", skip_serializing_if = "Option::is_none")]
    pub last_event_timestamp: Option<i64>,
}

impl Subscription {
    pub fn new(subscription_id: uuid::Uuid, venue: models::Venue, subscription_type: models::SubscriptionType, status: models::SubscriptionStatus, created_at: i64, updated_at: i64) -> Subscription {
        Subscription {
            subscription_id,
            venue,
            trading_account_id: None,
            instrument_id: None,
            subscription_type,
            status,
            created_at,
            created_at_date_time: None,
            updated_at,
            updated_at_date_time: None,
            last_event_timestamp: None,
        }
    }
}

