/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncMarketInstrumentsRequest {
    #[serde(rename = "venue")]
    pub venue: models::Venue,
    /// symbol list, example \\[\"BTC/ETH\",\"BTC/USDT\"\\]
    #[serde(rename = "symbols")]
    pub symbols: Vec<String>,
}

impl SyncMarketInstrumentsRequest {
    pub fn new(venue: models::Venue, symbols: Vec<String>) -> SyncMarketInstrumentsRequest {
        SyncMarketInstrumentsRequest { venue, symbols }
    }
}
