/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Ticker : Unified ticker payload. Used identically in REST responses (`GET /api/v3/market/ticker/_*`), WebSocket RPC results (`query.ticker.get` / `query.ticker.list`), and Centrifugo channel publications (`market:ticker:{venue}:{symbol}`, `market:ticker:{venue}`).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ticker {
    /// Instrument ID in format {VENUE}:{BASE}/{QUOTE}
    #[serde(rename = "instrumentId", skip_serializing_if = "Option::is_none")]
    pub instrument_id: Option<String>,
    #[serde(rename = "venue")]
    pub venue: models::Venue,
    /// Trading pair symbol in format {BASE}/{QUOTE}
    #[serde(rename = "symbol")]
    pub symbol: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "lastPrice", skip_serializing_if = "Option::is_none")]
    pub last_price: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "lastQuantity", skip_serializing_if = "Option::is_none")]
    pub last_quantity: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "bidPrice", skip_serializing_if = "Option::is_none")]
    pub bid_price: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "bidQuantity", skip_serializing_if = "Option::is_none")]
    pub bid_quantity: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "askPrice", skip_serializing_if = "Option::is_none")]
    pub ask_price: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "askQuantity", skip_serializing_if = "Option::is_none")]
    pub ask_quantity: Option<String>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
}

impl Ticker {
    /// Unified ticker payload. Used identically in REST responses (`GET /api/v3/market/ticker/_*`), WebSocket RPC results (`query.ticker.get` / `query.ticker.list`), and Centrifugo channel publications (`market:ticker:{venue}:{symbol}`, `market:ticker:{venue}`).
    pub fn new(venue: models::Venue, symbol: String, timestamp: i64) -> Ticker {
        Ticker {
            instrument_id: None,
            venue,
            symbol,
            last_price: None,
            last_quantity: None,
            bid_price: None,
            bid_quantity: None,
            ask_price: None,
            ask_quantity: None,
            timestamp,
        }
    }
}
