/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TradeExecution {
    /// UUID string
    #[serde(rename = "executionId")]
    pub execution_id: uuid::Uuid,
    /// Exchange's execution identifier
    #[serde(rename = "externalTradeId", skip_serializing_if = "Option::is_none")]
    pub external_trade_id: Option<String>,
    #[serde(rename = "venue")]
    pub venue: models::Venue,
    /// Instrument ID in format {VENUE}:{BASE}/{QUOTE}
    #[serde(rename = "instrumentId")]
    pub instrument_id: String,
    #[serde(rename = "orderSide", skip_serializing_if = "Option::is_none")]
    pub order_side: Option<models::OrderSide>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "executedQuantity")]
    pub executed_quantity: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "executedPrice")]
    pub executed_price: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "executedCost")]
    pub executed_cost: String,
    /// Fees charged for this execution
    #[serde(rename = "fees", skip_serializing_if = "Option::is_none")]
    pub fees: Option<Vec<models::SecurityQuantity>>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "executedAt")]
    pub executed_at: i64,
    /// Execution timestamp in ISO 8601 format
    #[serde(rename = "executedAtDateTime", skip_serializing_if = "Option::is_none")]
    pub executed_at_date_time: Option<String>,
}

impl TradeExecution {
    pub fn new(execution_id: uuid::Uuid, venue: models::Venue, instrument_id: String, executed_quantity: String, executed_price: String, executed_cost: String, executed_at: i64) -> TradeExecution {
        TradeExecution {
            execution_id,
            external_trade_id: None,
            venue,
            instrument_id,
            order_side: None,
            executed_quantity,
            executed_price,
            executed_cost,
            fees: None,
            executed_at,
            executed_at_date_time: None,
        }
    }
}

