/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TradingAccountCredential {
    /// UUID string
    #[serde(rename = "credentialId")]
    pub credential_id: uuid::Uuid,
    #[serde(rename = "venue")]
    pub venue: models::Venue,
    #[serde(rename = "credentialType", deserialize_with = "Option::deserialize")]
    pub credential_type: Option<models::CredentialType>,
    #[serde(rename = "nickname", skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
    #[serde(rename = "status")]
    pub status: models::TradingAccountCredentialStatus,
    /// Unix timestamp in milliseconds
    #[serde(rename = "createdAt")]
    pub created_at: i64,
    /// Creation timestamp in ISO 8601 format
    #[serde(rename = "createdAtDateTime", skip_serializing_if = "Option::is_none")]
    pub created_at_date_time: Option<String>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "updatedAt")]
    pub updated_at: i64,
    /// Last update timestamp in ISO 8601 format
    #[serde(rename = "updatedAtDateTime", skip_serializing_if = "Option::is_none")]
    pub updated_at_date_time: Option<String>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "revokedAt", skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<i64>,
    /// Revocation timestamp in ISO 8601 format
    #[serde(rename = "revokedAtDateTime", skip_serializing_if = "Option::is_none")]
    pub revoked_at_date_time: Option<String>,
}

impl TradingAccountCredential {
    pub fn new(
        credential_id: uuid::Uuid,
        venue: models::Venue,
        credential_type: Option<models::CredentialType>,
        status: models::TradingAccountCredentialStatus,
        created_at: i64,
        updated_at: i64,
    ) -> TradingAccountCredential {
        TradingAccountCredential {
            credential_id,
            venue,
            credential_type,
            nickname: None,
            status,
            created_at,
            created_at_date_time: None,
            updated_at,
            updated_at_date_time: None,
            revoked_at: None,
            revoked_at_date_time: None,
        }
    }
}
