/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TradeOrder {
    /// UUID string
    #[serde(rename = "tradeOrderId")]
    pub trade_order_id: uuid::Uuid,
    /// Exchange order list ID linking sibling orders in OCO/OTO/OTOCO order lists. Present on all orders in a list.
    #[serde(rename = "orderListId", skip_serializing_if = "Option::is_none")]
    pub order_list_id: Option<String>,
    /// Order list contingency type. Present on all orders in a list.
    #[serde(rename = "contingencyType", skip_serializing_if = "Option::is_none")]
    pub contingency_type: Option<ContingencyType>,
    /// UUID string
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
    #[serde(rename = "venue")]
    pub venue: models::Venue,
    /// UUID string
    #[serde(rename = "positionId", skip_serializing_if = "Option::is_none")]
    pub position_id: Option<uuid::Uuid>,
    /// Instrument ID in format {VENUE}:{BASE}/{QUOTE}
    #[serde(rename = "instrumentId")]
    pub instrument_id: String,
    /// UUID string
    #[serde(rename = "quoteId", skip_serializing_if = "Option::is_none")]
    pub quote_id: Option<uuid::Uuid>,
    /// Base asset in the trading pair
    #[serde(rename = "baseAsset")]
    pub base_asset: String,
    /// Quote asset in the trading pair
    #[serde(rename = "quoteAsset")]
    pub quote_asset: String,
    #[serde(rename = "orderSide")]
    pub order_side: models::OrderSide,
    #[serde(rename = "orderType", deserialize_with = "Option::deserialize")]
    pub order_type: Option<models::OrderType>,
    #[serde(rename = "timeInForce", deserialize_with = "Option::deserialize")]
    pub time_in_force: Option<models::TimeInForce>,
    #[serde(rename = "status", deserialize_with = "Option::deserialize")]
    pub status: Option<models::OrderStatus>,
    /// Reason for order rejection
    #[serde(rename = "rejectReason", skip_serializing_if = "Option::is_none")]
    pub reject_reason: Option<String>,
    /// Reason for order cancellation
    #[serde(rename = "cancelReason", skip_serializing_if = "Option::is_none")]
    pub cancel_reason: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "limitPrice", skip_serializing_if = "Option::is_none")]
    pub limit_price: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "stopPrice", skip_serializing_if = "Option::is_none")]
    pub stop_price: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "takeProfitPrice", skip_serializing_if = "Option::is_none")]
    pub take_profit_price: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(
        rename = "takeProfitLimitPrice",
        skip_serializing_if = "Option::is_none"
    )]
    pub take_profit_limit_price: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "stopLossPrice", skip_serializing_if = "Option::is_none")]
    pub stop_loss_price: Option<String>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "stopLossLimitPrice", skip_serializing_if = "Option::is_none")]
    pub stop_loss_limit_price: Option<String>,
    #[serde(
        rename = "takeProfitTimeInForce",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub take_profit_time_in_force: Option<Option<models::TimeInForce>>,
    #[serde(
        rename = "stopLossTimeInForce",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub stop_loss_time_in_force: Option<Option<models::TimeInForce>>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "quantity")]
    pub quantity: String,
    #[serde(rename = "orderQuantityType")]
    pub order_quantity_type: models::OrderQuantityType,
    #[serde(rename = "quantityRounding", skip_serializing_if = "Option::is_none")]
    pub quantity_rounding: Option<models::QuantityRounding>,
    /// Decimal value as string to preserve precision
    #[serde(rename = "executedPrice")]
    pub executed_price: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "executedQuantity")]
    pub executed_quantity: String,
    /// Decimal value as string to preserve precision
    #[serde(rename = "executedCost")]
    pub executed_cost: String,
    /// Aggregated fees across all executions
    #[serde(rename = "fees")]
    pub fees: Vec<models::SecurityQuantity>,
    /// Detailed breakdown of executions across different venues
    #[serde(rename = "executions", skip_serializing_if = "Option::is_none")]
    pub executions: Option<Vec<models::TradeExecution>>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "createdAt")]
    pub created_at: i64,
    /// Creation timestamp in ISO 8601 format
    #[serde(rename = "createdAtDateTime", skip_serializing_if = "Option::is_none")]
    pub created_at_date_time: Option<String>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "updatedAt")]
    pub updated_at: i64,
    /// Last update timestamp in ISO 8601 format
    #[serde(rename = "updatedAtDateTime", skip_serializing_if = "Option::is_none")]
    pub updated_at_date_time: Option<String>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "expireAt", skip_serializing_if = "Option::is_none")]
    pub expire_at: Option<i64>,
    /// Expiration timestamp in ISO 8601 format
    #[serde(rename = "expireAtDateTime", skip_serializing_if = "Option::is_none")]
    pub expire_at_date_time: Option<String>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "canceledAt", skip_serializing_if = "Option::is_none")]
    pub canceled_at: Option<i64>,
    /// Cancellation timestamp in ISO 8601 format
    #[serde(rename = "canceledAtDateTime", skip_serializing_if = "Option::is_none")]
    pub canceled_at_date_time: Option<String>,
}

impl TradeOrder {
    pub fn new(
        trade_order_id: uuid::Uuid,
        trading_account_id: uuid::Uuid,
        venue: models::Venue,
        instrument_id: String,
        base_asset: String,
        quote_asset: String,
        order_side: models::OrderSide,
        order_type: Option<models::OrderType>,
        time_in_force: Option<models::TimeInForce>,
        status: Option<models::OrderStatus>,
        quantity: String,
        order_quantity_type: models::OrderQuantityType,
        executed_price: String,
        executed_quantity: String,
        executed_cost: String,
        fees: Vec<models::SecurityQuantity>,
        created_at: i64,
        updated_at: i64,
    ) -> TradeOrder {
        TradeOrder {
            trade_order_id,
            order_list_id: None,
            contingency_type: None,
            trading_account_id,
            venue,
            position_id: None,
            instrument_id,
            quote_id: None,
            base_asset,
            quote_asset,
            order_side,
            order_type,
            time_in_force,
            status,
            reject_reason: None,
            cancel_reason: None,
            limit_price: None,
            stop_price: None,
            take_profit_price: None,
            take_profit_limit_price: None,
            stop_loss_price: None,
            stop_loss_limit_price: None,
            take_profit_time_in_force: None,
            stop_loss_time_in_force: None,
            quantity,
            order_quantity_type,
            quantity_rounding: None,
            executed_price,
            executed_quantity,
            executed_cost,
            fees,
            executions: None,
            created_at,
            created_at_date_time: None,
            updated_at,
            updated_at_date_time: None,
            expire_at: None,
            expire_at_date_time: None,
            canceled_at: None,
            canceled_at_date_time: None,
        }
    }
}
/// Order list contingency type. Present on all orders in a list.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContingencyType {
    #[serde(rename = "OCO")]
    Oco,
    #[serde(rename = "OTO")]
    Oto,
    #[serde(rename = "OTOCO")]
    Otoco,
}

impl Default for ContingencyType {
    fn default() -> ContingencyType {
        Self::Oco
    }
}
