/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TradingAccount {
    /// UUID string
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
    /// External trading account ID
    #[serde(rename = "externalTradingAccountId")]
    pub external_trading_account_id: String,
    #[serde(rename = "venue")]
    pub venue: models::Venue,
    /// Nickname of the trading account
    #[serde(rename = "nickname")]
    pub nickname: String,
    #[serde(rename = "accountType")]
    pub account_type: models::AccountType,
    /// Type of account on the exchange (set by market connector)
    #[serde(rename = "externalAccountType")]
    pub external_account_type: String,
    #[serde(rename = "positionMode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub position_mode: Option<Option<models::PositionMode>>,
    #[serde(rename = "collateralMode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub collateral_mode: Option<Option<models::CollateralMode>>,
    #[serde(rename = "marginMode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub margin_mode: Option<Option<models::MarginMode>>,
    #[serde(rename = "credentials")]
    pub credentials: Vec<models::TradingAccountCredential>,
    #[serde(rename = "status")]
    pub status: models::TradingAccountStatus,
    /// Unix timestamp in milliseconds
    #[serde(rename = "createdAt")]
    pub created_at: i64,
    /// Creation timestamp in ISO 8601 format
    #[serde(rename = "createdAtDateTime", skip_serializing_if = "Option::is_none")]
    pub created_at_date_time: Option<String>,
    /// Unix timestamp in milliseconds
    #[serde(rename = "updatedAt")]
    pub updated_at: i64,
    /// Last update timestamp in ISO 8601 format
    #[serde(rename = "updatedAtDateTime", skip_serializing_if = "Option::is_none")]
    pub updated_at_date_time: Option<String>,
}

impl TradingAccount {
    pub fn new(trading_account_id: uuid::Uuid, external_trading_account_id: String, venue: models::Venue, nickname: String, account_type: models::AccountType, external_account_type: String, credentials: Vec<models::TradingAccountCredential>, status: models::TradingAccountStatus, created_at: i64, updated_at: i64) -> TradingAccount {
        TradingAccount {
            trading_account_id,
            external_trading_account_id,
            venue,
            nickname,
            account_type,
            external_account_type,
            position_mode: None,
            collateral_mode: None,
            margin_mode: None,
            credentials,
            status,
            created_at,
            created_at_date_time: None,
            updated_at,
            updated_at_date_time: None,
        }
    }
}

