/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TradingAccountStatus : Status of the trading account
/// Status of the trading account
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TradingAccountStatus {
    #[serde(rename = "NEW")]
    New,
    #[serde(rename = "CREATED")]
    Created,
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "INACTIVE")]
    Inactive,
    #[serde(rename = "LOCKED")]
    Locked,
    #[serde(rename = "DISCONNECTED")]
    Disconnected,
    #[serde(rename = "UNAVAILABLE")]
    Unavailable,
}

impl std::fmt::Display for TradingAccountStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::New => write!(f, "NEW"),
            Self::Created => write!(f, "CREATED"),
            Self::Active => write!(f, "ACTIVE"),
            Self::Inactive => write!(f, "INACTIVE"),
            Self::Locked => write!(f, "LOCKED"),
            Self::Disconnected => write!(f, "DISCONNECTED"),
            Self::Unavailable => write!(f, "UNAVAILABLE"),
        }
    }
}

impl Default for TradingAccountStatus {
    fn default() -> TradingAccountStatus {
        Self::New
    }
}
