/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateType : How the client should apply the order book payload.  - `SNAPSHOT`: Full state of the book at `timestamp`. Client replaces its local view. - `DIFF`: Incremental change since previous message. Client applies per-level: zero quantity removes the level, non-zero upserts. - `DELTA`: Reconciliation delta against a known reference state (venue-specific semantics — document per-connector).
/// How the client should apply the order book payload.  - `SNAPSHOT`: Full state of the book at `timestamp`. Client replaces its local view. - `DIFF`: Incremental change since previous message. Client applies per-level: zero quantity removes the level, non-zero upserts. - `DELTA`: Reconciliation delta against a known reference state (venue-specific semantics — document per-connector).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UpdateType {
    #[serde(rename = "SNAPSHOT")]
    Snapshot,
    #[serde(rename = "DIFF")]
    Diff,
    #[serde(rename = "DELTA")]
    Delta,
}

impl std::fmt::Display for UpdateType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Snapshot => write!(f, "SNAPSHOT"),
            Self::Diff => write!(f, "DIFF"),
            Self::Delta => write!(f, "DELTA"),
        }
    }
}

impl Default for UpdateType {
    fn default() -> UpdateType {
        Self::Snapshot
    }
}
