/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTradingAccountRequest {
    /// UUID string
    #[serde(rename = "tradingAccountId")]
    pub trading_account_id: uuid::Uuid,
    /// New nickname for the trading account
    #[serde(rename = "nickname", skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
}

impl UpdateTradingAccountRequest {
    pub fn new(trading_account_id: uuid::Uuid) -> UpdateTradingAccountRequest {
        UpdateTradingAccountRequest {
            trading_account_id,
            nickname: None,
        }
    }
}

