/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VenueStatus : Venue status
/// Venue status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VenueStatus {
    #[serde(rename = "ONLINE")]
    Online,
    #[serde(rename = "OFFLINE")]
    Offline,
    #[serde(rename = "MAINTENANCE")]
    Maintenance,
}

impl std::fmt::Display for VenueStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Online => write!(f, "ONLINE"),
            Self::Offline => write!(f, "OFFLINE"),
            Self::Maintenance => write!(f, "MAINTENANCE"),
        }
    }
}

impl Default for VenueStatus {
    fn default() -> VenueStatus {
        Self::Online
    }
}
