/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WalletType : Type of Fermata wallet
/// Type of Fermata wallet
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WalletType {
    #[serde(rename = "DEALER")]
    Dealer,
    #[serde(rename = "CLIENT")]
    Client,
    #[serde(rename = "EXCHANGE")]
    Exchange,
    #[serde(rename = "ACCOUNTING")]
    Accounting,
}

impl std::fmt::Display for WalletType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Dealer => write!(f, "DEALER"),
            Self::Client => write!(f, "CLIENT"),
            Self::Exchange => write!(f, "EXCHANGE"),
            Self::Accounting => write!(f, "ACCOUNTING"),
        }
    }
}

impl Default for WalletType {
    fn default() -> WalletType {
        Self::Dealer
    }
}
