/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WalletStatus : Status of a Fermata wallet
/// Status of a Fermata wallet
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WalletStatus {
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "FROZEN")]
    Frozen,
    #[serde(rename = "CLOSED")]
    Closed,
}

impl std::fmt::Display for WalletStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Active => write!(f, "ACTIVE"),
            Self::Frozen => write!(f, "FROZEN"),
            Self::Closed => write!(f, "CLOSED"),
        }
    }
}

impl Default for WalletStatus {
    fn default() -> WalletStatus {
        Self::Active
    }
}
