/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsCommand : WebSocket command sent from client to server. Only one command field should be set per message.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsCommand {
    /// Unique command ID for request-response correlation
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "connect", skip_serializing_if = "Option::is_none")]
    pub connect: Option<Box<models::WsConnectRequest>>,
    #[serde(rename = "subscribe", skip_serializing_if = "Option::is_none")]
    pub subscribe: Option<Box<models::WsSubscribeRequest>>,
    #[serde(rename = "unsubscribe", skip_serializing_if = "Option::is_none")]
    pub unsubscribe: Option<Box<models::WsUnsubscribeRequest>>,
    #[serde(rename = "publish", skip_serializing_if = "Option::is_none")]
    pub publish: Option<Box<models::WsPublishRequest>>,
    #[serde(rename = "presence", skip_serializing_if = "Option::is_none")]
    pub presence: Option<Box<models::WsPresenceRequest>>,
    #[serde(rename = "presenceStats", skip_serializing_if = "Option::is_none")]
    pub presence_stats: Option<Box<models::WsPresenceStatsRequest>>,
    #[serde(rename = "history", skip_serializing_if = "Option::is_none")]
    pub history: Option<Box<models::WsHistoryRequest>>,
    /// Ping request to keep connection alive
    #[serde(rename = "ping", skip_serializing_if = "Option::is_none")]
    pub ping: Option<serde_json::Value>,
    #[serde(rename = "send", skip_serializing_if = "Option::is_none")]
    pub send: Option<Box<models::WsSendRequest>>,
    #[serde(rename = "rpc", skip_serializing_if = "Option::is_none")]
    pub rpc: Option<Box<models::WsRpcRequest>>,
    #[serde(rename = "refresh", skip_serializing_if = "Option::is_none")]
    pub refresh: Option<Box<models::WsRefreshRequest>>,
    #[serde(rename = "subRefresh", skip_serializing_if = "Option::is_none")]
    pub sub_refresh: Option<Box<models::WsSubRefreshRequest>>,
}

impl WsCommand {
    /// WebSocket command sent from client to server. Only one command field should be set per message.
    pub fn new(id: i32) -> WsCommand {
        WsCommand {
            id,
            connect: None,
            subscribe: None,
            unsubscribe: None,
            publish: None,
            presence: None,
            presence_stats: None,
            history: None,
            ping: None,
            send: None,
            rpc: None,
            refresh: None,
            sub_refresh: None,
        }
    }
}
