/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsClientInfo : Information about a connected client
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsClientInfo {
    /// User ID
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
    /// Client connection ID
    #[serde(rename = "client", skip_serializing_if = "Option::is_none")]
    pub client: Option<String>,
    /// Connection info set during authentication
    #[serde(rename = "connInfo", skip_serializing_if = "Option::is_none")]
    pub conn_info: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Channel info set during subscription
    #[serde(rename = "chanInfo", skip_serializing_if = "Option::is_none")]
    pub chan_info: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl WsClientInfo {
    /// Information about a connected client
    pub fn new() -> WsClientInfo {
        WsClientInfo {
            user: None,
            client: None,
            conn_info: None,
            chan_info: None,
        }
    }
}

