/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsDisconnect : Server-initiated disconnect notification
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsDisconnect {
    /// Disconnect reason code
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    /// Disconnect reason message
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Whether client should attempt to reconnect
    #[serde(rename = "reconnect", skip_serializing_if = "Option::is_none")]
    pub reconnect: Option<bool>,
}

impl WsDisconnect {
    /// Server-initiated disconnect notification
    pub fn new() -> WsDisconnect {
        WsDisconnect {
            code: None,
            reason: None,
            reconnect: None,
        }
    }
}
