/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsError : WebSocket error object returned when a command fails
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsError {
    /// Error code
    #[serde(rename = "code")]
    pub code: i32,
    /// Error message
    #[serde(rename = "message")]
    pub message: String,
    /// Whether the error is temporary and the command can be retried
    #[serde(rename = "temporary", skip_serializing_if = "Option::is_none")]
    pub temporary: Option<bool>,
}

impl WsError {
    /// WebSocket error object returned when a command fails
    pub fn new(code: i32, message: String) -> WsError {
        WsError {
            code,
            message,
            temporary: None,
        }
    }
}
