/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsLeave : Client leave notification
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsLeave {
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<Box<models::WsClientInfo>>,
}

impl WsLeave {
    /// Client leave notification
    pub fn new() -> WsLeave {
        WsLeave { info: None }
    }
}
