/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsMarketOrderBookSubscribeParams {
    #[serde(rename = "venue")]
    pub venue: models::Venue,
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "depth", skip_serializing_if = "Option::is_none")]
    pub depth: Option<i32>,
}

impl WsMarketOrderBookSubscribeParams {
    pub fn new(venue: models::Venue, symbol: String) -> WsMarketOrderBookSubscribeParams {
        WsMarketOrderBookSubscribeParams {
            venue,
            symbol,
            depth: None,
        }
    }
}
