/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsMarketOrderBookUpdate {
    #[serde(rename = "channel")]
    pub channel: Channel,
    #[serde(rename = "data")]
    pub data: Box<models::Orderbook>,
    /// UUID string
    #[serde(rename = "subscriptionId")]
    pub subscription_id: uuid::Uuid,
    /// Unix timestamp in milliseconds
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
}

impl WsMarketOrderBookUpdate {
    pub fn new(
        channel: Channel,
        data: models::Orderbook,
        subscription_id: uuid::Uuid,
        timestamp: i64,
    ) -> WsMarketOrderBookUpdate {
        WsMarketOrderBookUpdate {
            channel,
            data: Box::new(data),
            subscription_id,
            timestamp,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Channel {
    #[serde(rename = "market.orderBook")]
    MarketOrderBook,
}

impl Default for Channel {
    fn default() -> Channel {
        Self::MarketOrderBook
    }
}
