/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsPublishRequest : Publish a message to a channel
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsPublishRequest {
    /// Channel to publish to
    #[serde(rename = "channel")]
    pub channel: String,
    /// Message data to publish
    #[serde(rename = "data")]
    pub data: std::collections::HashMap<String, serde_json::Value>,
}

impl WsPublishRequest {
    /// Publish a message to a channel
    pub fn new(
        channel: String,
        data: std::collections::HashMap<String, serde_json::Value>,
    ) -> WsPublishRequest {
        WsPublishRequest { channel, data }
    }
}
