/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsPush : Server push message (asynchronous, id=0 in reply)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsPush {
    /// Channel the push is for
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<String>,
    #[serde(rename = "pub", skip_serializing_if = "Option::is_none")]
    pub r#pub: Option<Box<models::WsPublication>>,
    #[serde(rename = "join", skip_serializing_if = "Option::is_none")]
    pub join: Option<Box<models::WsJoin>>,
    #[serde(rename = "leave", skip_serializing_if = "Option::is_none")]
    pub leave: Option<Box<models::WsLeave>>,
    #[serde(rename = "unsubscribe", skip_serializing_if = "Option::is_none")]
    pub unsubscribe: Option<Box<models::WsUnsubscribePush>>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<Box<models::WsMessage>>,
    #[serde(rename = "subscribe", skip_serializing_if = "Option::is_none")]
    pub subscribe: Option<Box<models::WsSubscribePush>>,
    #[serde(rename = "connect", skip_serializing_if = "Option::is_none")]
    pub connect: Option<Box<models::WsConnectPush>>,
    #[serde(rename = "disconnect", skip_serializing_if = "Option::is_none")]
    pub disconnect: Option<Box<models::WsDisconnect>>,
    #[serde(rename = "refresh", skip_serializing_if = "Option::is_none")]
    pub refresh: Option<Box<models::WsRefreshPush>>,
}

impl WsPush {
    /// Server push message (asynchronous, id=0 in reply)
    pub fn new() -> WsPush {
        WsPush {
            channel: None,
            r#pub: None,
            join: None,
            leave: None,
            unsubscribe: None,
            message: None,
            subscribe: None,
            connect: None,
            disconnect: None,
            refresh: None,
        }
    }
}
