/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsPresenceStatsRequest : Request presence statistics for a channel
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsPresenceStatsRequest {
    /// Channel name
    #[serde(rename = "channel")]
    pub channel: String,
}

impl WsPresenceStatsRequest {
    /// Request presence statistics for a channel
    pub fn new(channel: String) -> WsPresenceStatsRequest {
        WsPresenceStatsRequest {
            channel,
        }
    }
}

