/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsPublication : Publication message containing channel data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsPublication {
    /// Publication payload
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<Box<models::WsClientInfo>>,
    /// Stream offset for recovery
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    /// Publication tags
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<std::collections::HashMap<String, String>>,
    /// Whether this is a delta update
    #[serde(rename = "delta", skip_serializing_if = "Option::is_none")]
    pub delta: Option<bool>,
    /// Publication time in milliseconds
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i64>,
    /// Channel name (for wildcard subscriptions)
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<String>,
}

impl WsPublication {
    /// Publication message containing channel data
    pub fn new() -> WsPublication {
        WsPublication {
            data: None,
            info: None,
            offset: None,
            tags: None,
            delta: None,
            time: None,
            channel: None,
        }
    }
}
