/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsRefreshRequest : Refresh connection credentials
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsRefreshRequest {
    /// New JWT token
    #[serde(rename = "token")]
    pub token: String,
}

impl WsRefreshRequest {
    /// Refresh connection credentials
    pub fn new(token: String) -> WsRefreshRequest {
        WsRefreshRequest { token }
    }
}
