/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsRpcRequestData : RPC request payload. Schema depends on the method being called.
/// RPC request payload. Schema depends on the method being called.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WsRpcRequestData {
    /// Request to get system information
    RpcGetSystemInfoParams(serde_json::Value),
    /// Request to check system health
    RpcHealthCheckParams(serde_json::Value),
    RpcSubmitTradeOrderParams(Box<models::RpcSubmitTradeOrderParams>),
    RpcCancelTradeOrderParams(Box<models::RpcCancelTradeOrderParams>),
    RpcGetTradeOrderParams(Box<models::RpcGetTradeOrderParams>),
    RpcGetTradeOrderByIdParams(Box<models::RpcGetTradeOrderByIdParams>),
    RpcListTradeOrdersParams(Box<models::RpcListTradeOrdersParams>),
    RpcSaveTradeOrderParams(Box<models::RpcSaveTradeOrderParams>),
    RpcCreateTradingAccountParams(Box<models::RpcCreateTradingAccountParams>),
    RpcSaveTradingAccountsParams(Box<models::RpcSaveTradingAccountsParams>),
    RpcUpdateTradingAccountParams(Box<models::RpcUpdateTradingAccountParams>),
    RpcDeleteTradingAccountParams(Box<models::RpcDeleteTradingAccountParams>),
    RpcValidateTradingAccountParams(Box<models::RpcValidateTradingAccountParams>),
    RpcConnectTradingAccountParams(Box<models::RpcConnectTradingAccountParams>),
    RpcDisconnectTradingAccountParams(Box<models::RpcDisconnectTradingAccountParams>),
    RpcEnableTradingAccountParams(Box<models::RpcEnableTradingAccountParams>),
    RpcDisableTradingAccountParams(Box<models::RpcDisableTradingAccountParams>),
    RpcListTradingAccountsParams(Box<models::RpcListTradingAccountsParams>),
    RpcListTradingAccountOperationsParams(Box<models::RpcListTradingAccountOperationsParams>),
    RpcSubscribeTradingAccountStreamParams(Box<models::RpcSubscribeTradingAccountStreamParams>),
    RpcUnsubscribeTradingAccountStreamParams(Box<models::RpcUnsubscribeTradingAccountStreamParams>),
    RpcListTradingAccountSubscriptionsParams(Box<models::RpcListTradingAccountSubscriptionsParams>),
    RpcCreateCredentialParams(Box<models::RpcCreateCredentialParams>),
    RpcSaveCredentialParams(Box<models::RpcSaveCredentialParams>),
    RpcListCredentialsParams(Box<models::RpcListCredentialsParams>),
    RpcVerifyCredentialParams(Box<models::RpcVerifyCredentialParams>),
    RpcRevokeCredentialParams(Box<models::RpcRevokeCredentialParams>),
    RpcRotateCredentialParams(Box<models::RpcRotateCredentialParams>),
    RpcGetPortfolioParams(Box<models::RpcGetPortfolioParams>),
    RpcListPortfoliosParams(Box<models::RpcListPortfoliosParams>),
    RpcSavePortfolioParams(Box<models::RpcSavePortfolioParams>),
    RpcSyncInstrumentsParams(Box<models::RpcSyncInstrumentsParams>),
    RpcSaveInstrumentsParams(Box<models::RpcSaveInstrumentsParams>),
    RpcListInstrumentsParams(Box<models::RpcListInstrumentsParams>),
    RpcDeleteInstrumentParams(Box<models::RpcDeleteInstrumentParams>),
    RpcEnableInstrumentParams(Box<models::RpcEnableInstrumentParams>),
    RpcDisableInstrumentParams(Box<models::RpcDisableInstrumentParams>),
    RpcSyncSecuritiesParams(Box<models::RpcSyncSecuritiesParams>),
    RpcSaveSecuritiesParams(Box<models::RpcSaveSecuritiesParams>),
    RpcDeleteSecuritiesParams(Box<models::RpcDeleteSecuritiesParams>),
    RpcListSecuritiesParams(Box<models::RpcListSecuritiesParams>),
    /// Request to list available venues
    RpcListVenuesParams(serde_json::Value),
    RpcGetOrderBookParams(Box<models::RpcGetOrderBookParams>),
    RpcListOrderBooksParams(Box<models::RpcListOrderBooksParams>),
    RpcSaveOrderBooksParams(Box<models::RpcSaveOrderBooksParams>),
    RpcSubscribeOrderBookParams(Box<models::RpcSubscribeOrderBookParams>),
    RpcUnsubscribeOrderBookParams(Box<models::RpcUnsubscribeOrderBookParams>),
    RpcListOrderBookSubscriptionsParams(Box<models::RpcListOrderBookSubscriptionsParams>),
    RpcSaveKlinesParams(Box<models::RpcSaveKlinesParams>),
    RpcListKlinesParams(Box<models::RpcListKlinesParams>),
    RpcSaveTickersParams(Box<models::RpcSaveTickersParams>),
    RpcListTickersParams(Box<models::RpcListTickersParams>),
    RpcCreateSubscriptionParams(Box<models::RpcCreateSubscriptionParams>),
    RpcListSubscriptionsParams(Box<models::RpcListSubscriptionsParams>),
}

impl Default for WsRpcRequestData {
    fn default() -> Self {
        Self::RpcGetSystemInfoParams(Default::default())
    }
}

