/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsReply : WebSocket reply sent from server to client. The id field is zero for server-initiated pushes.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsReply {
    /// Command ID matching the request (0 for pushes)
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::WsError>>,
    #[serde(rename = "push", skip_serializing_if = "Option::is_none")]
    pub push: Option<Box<models::WsPush>>,
    #[serde(rename = "connect", skip_serializing_if = "Option::is_none")]
    pub connect: Option<Box<models::WsConnectResult>>,
    #[serde(rename = "subscribe", skip_serializing_if = "Option::is_none")]
    pub subscribe: Option<Box<models::WsSubscribeResult>>,
    /// Unsubscribe result (empty on success)
    #[serde(rename = "unsubscribe", skip_serializing_if = "Option::is_none")]
    pub unsubscribe: Option<serde_json::Value>,
    /// Publish result (empty on success)
    #[serde(rename = "publish", skip_serializing_if = "Option::is_none")]
    pub publish: Option<serde_json::Value>,
    #[serde(rename = "presence", skip_serializing_if = "Option::is_none")]
    pub presence: Option<Box<models::WsPresenceResult>>,
    #[serde(rename = "presenceStats", skip_serializing_if = "Option::is_none")]
    pub presence_stats: Option<Box<models::WsPresenceStatsResult>>,
    #[serde(rename = "history", skip_serializing_if = "Option::is_none")]
    pub history: Option<Box<models::WsHistoryResult>>,
    /// Pong response
    #[serde(rename = "ping", skip_serializing_if = "Option::is_none")]
    pub ping: Option<serde_json::Value>,
    #[serde(rename = "rpc", skip_serializing_if = "Option::is_none")]
    pub rpc: Option<Box<models::WsRpcResult>>,
    #[serde(rename = "refresh", skip_serializing_if = "Option::is_none")]
    pub refresh: Option<Box<models::WsRefreshResult>>,
    #[serde(rename = "subRefresh", skip_serializing_if = "Option::is_none")]
    pub sub_refresh: Option<Box<models::WsSubRefreshResult>>,
}

impl WsReply {
    /// WebSocket reply sent from server to client. The id field is zero for server-initiated pushes.
    pub fn new() -> WsReply {
        WsReply {
            id: None,
            error: None,
            push: None,
            connect: None,
            subscribe: None,
            unsubscribe: None,
            publish: None,
            presence: None,
            presence_stats: None,
            history: None,
            ping: None,
            rpc: None,
            refresh: None,
            sub_refresh: None,
        }
    }
}

