/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsSubscribePush : Server-initiated subscribe notification
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsSubscribePush {
    #[serde(rename = "recoverable", skip_serializing_if = "Option::is_none")]
    pub recoverable: Option<bool>,
    #[serde(rename = "epoch", skip_serializing_if = "Option::is_none")]
    pub epoch: Option<String>,
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    #[serde(rename = "positioned", skip_serializing_if = "Option::is_none")]
    pub positioned: Option<bool>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl WsSubscribePush {
    /// Server-initiated subscribe notification
    pub fn new() -> WsSubscribePush {
        WsSubscribePush {
            recoverable: None,
            epoch: None,
            offset: None,
            positioned: None,
            data: None,
        }
    }
}
