/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsStreamPosition : Stream position for history recovery
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsStreamPosition {
    /// Stream offset
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    /// Stream epoch
    #[serde(rename = "epoch", skip_serializing_if = "Option::is_none")]
    pub epoch: Option<String>,
}

impl WsStreamPosition {
    /// Stream position for history recovery
    pub fn new() -> WsStreamPosition {
        WsStreamPosition {
            offset: None,
            epoch: None,
        }
    }
}

