/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsSubscribeRequest : Subscribe to a channel for real-time updates
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsSubscribeRequest {
    /// Channel name to subscribe to
    #[serde(rename = "channel")]
    pub channel: String,
    /// Subscription token (for private channels)
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// Whether to recover missed messages
    #[serde(rename = "recover", skip_serializing_if = "Option::is_none")]
    pub recover: Option<bool>,
    /// Stream epoch for recovery
    #[serde(rename = "epoch", skip_serializing_if = "Option::is_none")]
    pub epoch: Option<String>,
    /// Stream offset for recovery
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    /// Custom subscription data
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Whether to receive position info in publications
    #[serde(rename = "positioned", skip_serializing_if = "Option::is_none")]
    pub positioned: Option<bool>,
    /// Whether the subscription should be recoverable
    #[serde(rename = "recoverable", skip_serializing_if = "Option::is_none")]
    pub recoverable: Option<bool>,
    /// Whether to receive join/leave messages
    #[serde(rename = "joinLeave", skip_serializing_if = "Option::is_none")]
    pub join_leave: Option<bool>,
    /// Delta compression mode
    #[serde(rename = "delta", skip_serializing_if = "Option::is_none")]
    pub delta: Option<String>,
}

impl WsSubscribeRequest {
    /// Subscribe to a channel for real-time updates
    pub fn new(channel: String) -> WsSubscribeRequest {
        WsSubscribeRequest {
            channel,
            token: None,
            recover: None,
            epoch: None,
            offset: None,
            data: None,
            positioned: None,
            recoverable: None,
            join_leave: None,
            delta: None,
        }
    }
}

