/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsSendRequest : Send asynchronous message (no reply expected)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsSendRequest {
    /// Message data
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl WsSendRequest {
    /// Send asynchronous message (no reply expected)
    pub fn new() -> WsSendRequest {
        WsSendRequest {
            data: None,
        }
    }
}

