/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsSubRefreshRequest : Refresh subscription credentials
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsSubRefreshRequest {
    /// Channel to refresh
    #[serde(rename = "channel")]
    pub channel: String,
    /// New subscription token
    #[serde(rename = "token")]
    pub token: String,
}

impl WsSubRefreshRequest {
    /// Refresh subscription credentials
    pub fn new(channel: String, token: String) -> WsSubRefreshRequest {
        WsSubRefreshRequest { channel, token }
    }
}
