/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsUnsubscribePush : Server-initiated unsubscribe notification
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsUnsubscribePush {
    /// Unsubscribe reason code
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
    /// Unsubscribe reason message
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl WsUnsubscribePush {
    /// Server-initiated unsubscribe notification
    pub fn new() -> WsUnsubscribePush {
        WsUnsubscribePush {
            code: None,
            reason: None,
        }
    }
}
