/*
 * Algo724 Cadenza Fermata API
 *
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsUnsubscribeRequest : Unsubscribe from a channel
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsUnsubscribeRequest {
    /// Channel name to unsubscribe from
    #[serde(rename = "channel")]
    pub channel: String,
}

impl WsUnsubscribeRequest {
    /// Unsubscribe from a channel
    pub fn new(channel: String) -> WsUnsubscribeRequest {
        WsUnsubscribeRequest {
            channel,
        }
    }
}

