// Auto-generated by openapi-generator — suppress clippy lints for generated code
#![allow(unused_imports)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::needless_return)]
#![allow(clippy::empty_line_after_doc_comments)]
#![allow(clippy::into_iter_on_ref)]
#![allow(clippy::derivable_impls)]
#![allow(clippy::empty_docs)]
#![allow(clippy::uninlined_format_args)]

extern crate reqwest;
extern crate serde;
extern crate serde_json;
extern crate serde_repr;
extern crate url;

pub mod apis;
pub mod models;
